/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class BuiltinTopicKey_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BuiltinTopicKey_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BuiltinTopicKey_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_BuiltinTopicKey_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(int[] value) {
    cpsjavamoduleJNI.BuiltinTopicKey_t_value_set(swigCPtr, this, value);
  }

  public int[] getValue() {
    return cpsjavamoduleJNI.BuiltinTopicKey_t_value_get(swigCPtr, this);
  }

  public BuiltinTopicKey_t() {
    this(cpsjavamoduleJNI.new_BuiltinTopicKey_t(), true);
  }

}
