/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class ConditionSeq {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConditionSeq(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConditionSeq obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_ConditionSeq(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI_seq(int value) {
    cpsjavamoduleJNI.ConditionSeq_i_seq_set(swigCPtr, this, value);
  }

  public int getI_seq() {
    return cpsjavamoduleJNI.ConditionSeq_i_seq_get(swigCPtr, this);
  }

  public void setPp_conditions(SWIGTYPE_p_p_Condition value) {
    cpsjavamoduleJNI.ConditionSeq_pp_conditions_set(swigCPtr, this, SWIGTYPE_p_p_Condition.getCPtr(value));
  }

  public SWIGTYPE_p_p_Condition getPp_conditions() {
    long cPtr = cpsjavamoduleJNI.ConditionSeq_pp_conditions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_Condition(cPtr, false);
  }

  public ConditionSeq() {
    this(cpsjavamoduleJNI.new_ConditionSeq(), true);
  }

}
