/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class ConditionSeq2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConditionSeq2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConditionSeq2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_ConditionSeq2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ConditionSeq2() {
    this(cpsjavamoduleJNI.new_ConditionSeq2(), true);
  }

  public ConditionSeq getConditionSeq() {
    return new ConditionSeq(cpsjavamoduleJNI.ConditionSeq2_getConditionSeq(swigCPtr, this), true);
  }

  public ConditionSeq getConditionSeqPtr() {
    long cPtr = cpsjavamoduleJNI.ConditionSeq2_getConditionSeqPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new ConditionSeq(cPtr, false);
  }

}
