/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class Condition2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Condition2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Condition2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_Condition2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Condition2(Condition condition) {
    this(cpsjavamoduleJNI.new_Condition2(Condition.getCPtr(condition), condition), true);
  }

  public Condition getCondition() {
    long cPtr = cpsjavamoduleJNI.Condition2_getCondition(swigCPtr, this);
    return (cPtr == 0) ? null : new Condition(cPtr, false);
  }

  public boolean get_trigger_value() {
    return cpsjavamoduleJNI.Condition2_get_trigger_value(swigCPtr, this);
  }

}
