/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class cpsjavamodule implements cpsjavamoduleConstants {
  public static int getINVALID_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.INVALID_QOS_POLICY_ID_get();
  }

  public static int getUSERDATA_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.USERDATA_QOS_POLICY_ID_get();
  }

  public static int getDURABILITY_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.DURABILITY_QOS_POLICY_ID_get();
  }

  public static int getPRESENTATION_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.PRESENTATION_QOS_POLICY_ID_get();
  }

  public static int getDEADLINE_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.DEADLINE_QOS_POLICY_ID_get();
  }

  public static int getLATENCYBUDGET_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.LATENCYBUDGET_QOS_POLICY_ID_get();
  }

  public static int getOWNERSHIP_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.OWNERSHIP_QOS_POLICY_ID_get();
  }

  public static int getOWNERSHIPSTRENGTH_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.OWNERSHIPSTRENGTH_QOS_POLICY_ID_get();
  }

  public static int getLIVELINESS_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.LIVELINESS_QOS_POLICY_ID_get();
  }

  public static int getTIMEBASEDFILTER_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.TIMEBASEDFILTER_QOS_POLICY_ID_get();
  }

  public static int getPARTITION_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.PARTITION_QOS_POLICY_ID_get();
  }

  public static int getRELIABILITY_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.RELIABILITY_QOS_POLICY_ID_get();
  }

  public static int getDESTINATIONORDER_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.DESTINATIONORDER_QOS_POLICY_ID_get();
  }

  public static int getHISTORY_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.HISTORY_QOS_POLICY_ID_get();
  }

  public static int getRESOURCELIMITS_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.RESOURCELIMITS_QOS_POLICY_ID_get();
  }

  public static int getENTITYFACTORY_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.ENTITYFACTORY_QOS_POLICY_ID_get();
  }

  public static int getWRITERDATALIFECYCLE_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.WRITERDATALIFECYCLE_QOS_POLICY_ID_get();
  }

  public static int getREADERDATALIFECYCLE_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.READERDATALIFECYCLE_QOS_POLICY_ID_get();
  }

  public static int getTOPICDATA_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.TOPICDATA_QOS_POLICY_ID_get();
  }

  public static int getGROUPDATA_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.GROUPDATA_QOS_POLICY_ID_get();
  }

  public static int getTRANSPORTPRIORITY_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.TRANSPORTPRIORITY_QOS_POLICY_ID_get();
  }

  public static int getLIFESPAN_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.LIFESPAN_QOS_POLICY_ID_get();
  }

  public static int getDURABILITYSERVICE_QOS_POLICY_ID() {
    return cpsjavamoduleJNI.DURABILITYSERVICE_QOS_POLICY_ID_get();
  }

  public static long getINCONSISTENT_TOPIC_STATUS() {
    return cpsjavamoduleJNI.INCONSISTENT_TOPIC_STATUS_get();
  }

  public static long getOFFERED_DEADLINE_MISSED_STATUS() {
    return cpsjavamoduleJNI.OFFERED_DEADLINE_MISSED_STATUS_get();
  }

  public static long getREQUESTED_DEADLINE_MISSED_STATUS() {
    return cpsjavamoduleJNI.REQUESTED_DEADLINE_MISSED_STATUS_get();
  }

  public static long getOFFERED_INCOMPATIBLE_QOS_STATUS() {
    return cpsjavamoduleJNI.OFFERED_INCOMPATIBLE_QOS_STATUS_get();
  }

  public static long getREQUESTED_INCOMPATIBLE_QOS_STATUS() {
    return cpsjavamoduleJNI.REQUESTED_INCOMPATIBLE_QOS_STATUS_get();
  }

  public static long getSAMPLE_LOST_STATUS() {
    return cpsjavamoduleJNI.SAMPLE_LOST_STATUS_get();
  }

  public static long getSAMPLE_REJECTED_STATUS() {
    return cpsjavamoduleJNI.SAMPLE_REJECTED_STATUS_get();
  }

  public static long getDATA_ON_READERS_STATUS() {
    return cpsjavamoduleJNI.DATA_ON_READERS_STATUS_get();
  }

  public static long getDATA_AVAILABLE_STATUS() {
    return cpsjavamoduleJNI.DATA_AVAILABLE_STATUS_get();
  }

  public static long getLIVELINESS_LOST_STATUS() {
    return cpsjavamoduleJNI.LIVELINESS_LOST_STATUS_get();
  }

  public static long getLIVELINESS_CHANGED_STATUS() {
    return cpsjavamoduleJNI.LIVELINESS_CHANGED_STATUS_get();
  }

  public static long getPUBLICATION_MATCHED_STATUS() {
    return cpsjavamoduleJNI.PUBLICATION_MATCHED_STATUS_get();
  }

  public static long getSUBSCRIPTION_MATCHED_STATUS() {
    return cpsjavamoduleJNI.SUBSCRIPTION_MATCHED_STATUS_get();
  }

  public static long getALL_ENABLE_STATUS() {
    return cpsjavamoduleJNI.ALL_ENABLE_STATUS_get();
  }

}
