/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class DataWriterListenerStatusChangedFlag {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataWriterListenerStatusChangedFlag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataWriterListenerStatusChangedFlag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_DataWriterListenerStatusChangedFlag(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setB_liveliness_lost_status_changed_flag(boolean value) {
    cpsjavamoduleJNI.DataWriterListenerStatusChangedFlag_b_liveliness_lost_status_changed_flag_set(swigCPtr, this, value);
  }

  public boolean getB_liveliness_lost_status_changed_flag() {
    return cpsjavamoduleJNI.DataWriterListenerStatusChangedFlag_b_liveliness_lost_status_changed_flag_get(swigCPtr, this);
  }

  public void setB_offered_deadline_missed_status_changed_flag(boolean value) {
    cpsjavamoduleJNI.DataWriterListenerStatusChangedFlag_b_offered_deadline_missed_status_changed_flag_set(swigCPtr, this, value);
  }

  public boolean getB_offered_deadline_missed_status_changed_flag() {
    return cpsjavamoduleJNI.DataWriterListenerStatusChangedFlag_b_offered_deadline_missed_status_changed_flag_get(swigCPtr, this);
  }

  public void setB_offered_incompatible_qos_status_changed_flag(boolean value) {
    cpsjavamoduleJNI.DataWriterListenerStatusChangedFlag_b_offered_incompatible_qos_status_changed_flag_set(swigCPtr, this, value);
  }

  public boolean getB_offered_incompatible_qos_status_changed_flag() {
    return cpsjavamoduleJNI.DataWriterListenerStatusChangedFlag_b_offered_incompatible_qos_status_changed_flag_get(swigCPtr, this);
  }

  public void setB_publication_matched_status_changed_flag(boolean value) {
    cpsjavamoduleJNI.DataWriterListenerStatusChangedFlag_b_publication_matched_status_changed_flag_set(swigCPtr, this, value);
  }

  public boolean getB_publication_matched_status_changed_flag() {
    return cpsjavamoduleJNI.DataWriterListenerStatusChangedFlag_b_publication_matched_status_changed_flag_get(swigCPtr, this);
  }

  public DataWriterListenerStatusChangedFlag() {
    this(cpsjavamoduleJNI.new_DataWriterListenerStatusChangedFlag(), true);
  }

}
