/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class DataReaderQos {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataReaderQos(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataReaderQos obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_DataReaderQos(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDurability(DurabilityQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_durability_set(swigCPtr, this, DurabilityQosPolicy.getCPtr(value), value);
  }

  public DurabilityQosPolicy getDurability() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_durability_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DurabilityQosPolicy(cPtr, false);
  }

  public void setDeadline(DeadlineQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_deadline_set(swigCPtr, this, DeadlineQosPolicy.getCPtr(value), value);
  }

  public DeadlineQosPolicy getDeadline() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_deadline_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DeadlineQosPolicy(cPtr, false);
  }

  public void setLatency_budget(LatencyBudgetQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_latency_budget_set(swigCPtr, this, LatencyBudgetQosPolicy.getCPtr(value), value);
  }

  public LatencyBudgetQosPolicy getLatency_budget() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_latency_budget_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LatencyBudgetQosPolicy(cPtr, false);
  }

  public void setLiveliness(LivelinessQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_liveliness_set(swigCPtr, this, LivelinessQosPolicy.getCPtr(value), value);
  }

  public LivelinessQosPolicy getLiveliness() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_liveliness_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LivelinessQosPolicy(cPtr, false);
  }

  public void setReliability(ReliabilityQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_reliability_set(swigCPtr, this, ReliabilityQosPolicy.getCPtr(value), value);
  }

  public ReliabilityQosPolicy getReliability() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_reliability_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ReliabilityQosPolicy(cPtr, false);
  }

  public void setDestination_order(DestinationOrderQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_destination_order_set(swigCPtr, this, DestinationOrderQosPolicy.getCPtr(value), value);
  }

  public DestinationOrderQosPolicy getDestination_order() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_destination_order_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DestinationOrderQosPolicy(cPtr, false);
  }

  public void setHistory(HistoryQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_history_set(swigCPtr, this, HistoryQosPolicy.getCPtr(value), value);
  }

  public HistoryQosPolicy getHistory() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_history_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HistoryQosPolicy(cPtr, false);
  }

  public void setResource_limits(ResourceLimitsQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_resource_limits_set(swigCPtr, this, ResourceLimitsQosPolicy.getCPtr(value), value);
  }

  public ResourceLimitsQosPolicy getResource_limits() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_resource_limits_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ResourceLimitsQosPolicy(cPtr, false);
  }

  public void setUser_data(UserDataQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_user_data_set(swigCPtr, this, UserDataQosPolicy.getCPtr(value), value);
  }

  public UserDataQosPolicy getUser_data() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_user_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UserDataQosPolicy(cPtr, false);
  }

  public void setOwnership(OwnershipQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_ownership_set(swigCPtr, this, OwnershipQosPolicy.getCPtr(value), value);
  }

  public OwnershipQosPolicy getOwnership() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_ownership_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OwnershipQosPolicy(cPtr, false);
  }

  public void setTime_based_filter(TimeBasedFilterQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_time_based_filter_set(swigCPtr, this, TimeBasedFilterQosPolicy.getCPtr(value), value);
  }

  public TimeBasedFilterQosPolicy getTime_based_filter() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_time_based_filter_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TimeBasedFilterQosPolicy(cPtr, false);
  }

  public void setReader_data_lifecycle(ReaderDataLifecycleQosPolicy value) {
    cpsjavamoduleJNI.DataReaderQos_reader_data_lifecycle_set(swigCPtr, this, ReaderDataLifecycleQosPolicy.getCPtr(value), value);
  }

  public ReaderDataLifecycleQosPolicy getReader_data_lifecycle() {
    long cPtr = cpsjavamoduleJNI.DataReaderQos_reader_data_lifecycle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ReaderDataLifecycleQosPolicy(cPtr, false);
  }

  public DataReaderQos() {
    this(cpsjavamoduleJNI.new_DataReaderQos(), true);
  }

}
