/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class DataWriterListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataWriterListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataWriterListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_DataWriterListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNot_used(int value) {
    cpsjavamoduleJNI.DataWriterListener_not_used_set(swigCPtr, this, value);
  }

  public int getNot_used() {
    return cpsjavamoduleJNI.DataWriterListener_not_used_get(swigCPtr, this);
  }

  public DataWriterListener() {
    this(cpsjavamoduleJNI.new_DataWriterListener(), true);
  }

}
