/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class DataWriter2 extends Entity2 {
  private long swigCPtr;

  protected DataWriter2(long cPtr, boolean cMemoryOwn) {
    super(cpsjavamoduleJNI.DataWriter2_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataWriter2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_DataWriter2(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DataWriter2(DataWriter dataWriter) {
    this(cpsjavamoduleJNI.new_DataWriter2(DataWriter.getCPtr(dataWriter), dataWriter), true);
  }

  public DataWriter getDataWriter() {
    long cPtr = cpsjavamoduleJNI.DataWriter2_getDataWriter(swigCPtr, this);
    return (cPtr == 0) ? null : new DataWriter(cPtr, false);
  }

  public int set_qos(DataWriterQos qos) {
    return cpsjavamoduleJNI.DataWriter2_set_qos(swigCPtr, this, DataWriterQos.getCPtr(qos), qos);
  }

  public int get_qos(DataWriterQos qos) {
    return cpsjavamoduleJNI.DataWriter2_get_qos(swigCPtr, this, DataWriterQos.getCPtr(qos), qos);
  }

  public int set_listener(DataWriterListener2 listener, long mask) {
    return cpsjavamoduleJNI.DataWriter2_set_listener(swigCPtr, this, DataWriterListener2.getCPtr(listener), listener, mask);
  }

  public DataWriterListener2 get_listener() {
    return new DataWriterListener2(cpsjavamoduleJNI.DataWriter2_get_listener(swigCPtr, this), true);
  }

  public Topic2 get_topic() {
    return new Topic2(cpsjavamoduleJNI.DataWriter2_get_topic(swigCPtr, this), true);
  }

  public Publisher2 get_publisher() {
    return new Publisher2(cpsjavamoduleJNI.DataWriter2_get_publisher(swigCPtr, this), true);
  }

  public int wait_for_acknowledgments(Duration_t max_wait) {
    return cpsjavamoduleJNI.DataWriter2_wait_for_acknowledgments(swigCPtr, this, Duration_t.getCPtr(max_wait), max_wait);
  }

  public int get_liveliness_lost_status(LivelinessLostStatus status) {
    return cpsjavamoduleJNI.DataWriter2_get_liveliness_lost_status(swigCPtr, this, LivelinessLostStatus.getCPtr(status), status);
  }

  public int get_offered_deadline_missed_status(OfferedDeadlineMissedStatus status) {
    return cpsjavamoduleJNI.DataWriter2_get_offered_deadline_missed_status(swigCPtr, this, OfferedDeadlineMissedStatus.getCPtr(status), status);
  }

  public int get_offered_incompatible_qos_status(OfferedIncompatibleQosStatus status) {
    return cpsjavamoduleJNI.DataWriter2_get_offered_incompatible_qos_status(swigCPtr, this, OfferedIncompatibleQosStatus.getCPtr(status), status);
  }

  public int get_publication_matched_status(PublicationMatchedStatus status) {
    return cpsjavamoduleJNI.DataWriter2_get_publication_matched_status(swigCPtr, this, PublicationMatchedStatus.getCPtr(status), status);
  }

  public int assert_liveliness() {
    return cpsjavamoduleJNI.DataWriter2_assert_liveliness(swigCPtr, this);
  }

  public int get_matched_subscriptions(InstanceHandleSeq subscription_handles) {
    return cpsjavamoduleJNI.DataWriter2_get_matched_subscriptions(swigCPtr, this, InstanceHandleSeq.getCPtr(subscription_handles), subscription_handles);
  }

  public int get_matched_subscription_data(SubscriptionBuiltinTopicData subscription_data, int subscription_handle) {
    return cpsjavamoduleJNI.DataWriter2_get_matched_subscription_data(swigCPtr, this, SubscriptionBuiltinTopicData.getCPtr(subscription_data), subscription_data, subscription_handle);
  }

}
