/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class DataReaderListenerCallBack {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataReaderListenerCallBack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataReaderListenerCallBack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_DataReaderListenerCallBack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    cpsjavamoduleJNI.DataReaderListenerCallBack_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    cpsjavamoduleJNI.DataReaderListenerCallBack_change_ownership(this, swigCPtr, true);
  }

  public void on_inconsistent_topic(Topic the_topic, InconsistentTopicStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_inconsistent_topic(swigCPtr, this, Topic.getCPtr(the_topic), the_topic, InconsistentTopicStatus.getCPtr(status), status);
  }

  public void on_offered_deadline_missed(DataWriter writer, OfferedDeadlineMissedStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_offered_deadline_missed(swigCPtr, this, DataWriter.getCPtr(writer), writer, OfferedDeadlineMissedStatus.getCPtr(status), status);
  }

  public void on_offered_incompatible_qos(DataWriter writer, OfferedIncompatibleQosStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_offered_incompatible_qos(swigCPtr, this, DataWriter.getCPtr(writer), writer, OfferedIncompatibleQosStatus.getCPtr(status), status);
  }

  public void on_liveliness_lost(DataWriter writer, LivelinessLostStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_liveliness_lost(swigCPtr, this, DataWriter.getCPtr(writer), writer, LivelinessLostStatus.getCPtr(status), status);
  }

  public void on_publication_matched(DataWriter writer, PublicationMatchedStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_publication_matched(swigCPtr, this, DataWriter.getCPtr(writer), writer, PublicationMatchedStatus.getCPtr(status), status);
  }

  public void on_requested_deadline_missed(DataReader the_reader, RequestedDeadlineMissedStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_requested_deadline_missed(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, RequestedDeadlineMissedStatus.getCPtr(status), status);
  }

  public void on_requested_incompatible_qos(DataReader the_reader, RequestedIncompatibleQosStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_requested_incompatible_qos(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, RequestedIncompatibleQosStatus.getCPtr(status), status);
  }

  public void on_sample_rejected(DataReader the_reader, SampleRejectedStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_sample_rejected(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, SampleRejectedStatus.getCPtr(status), status);
  }

  public void on_liveliness_changed(DataReader the_reader, LivelinessChangedStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_liveliness_changed(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, LivelinessChangedStatus.getCPtr(status), status);
  }

  public void on_data_available(DataReader p_reader) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_data_available(swigCPtr, this, DataReader.getCPtr(p_reader), p_reader);
  }

  public void on_subscription_matched(DataReader the_reader, SubscriptionMatchedStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_subscription_matched(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, SubscriptionMatchedStatus.getCPtr(status), status);
  }

  public void on_sample_lost(DataReader the_reader, SampleLostStatus status) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_sample_lost(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, SampleLostStatus.getCPtr(status), status);
  }

  public void on_data_on_readers(Subscriber p_subscriber) {
    cpsjavamoduleJNI.DataReaderListenerCallBack_on_data_on_readers(swigCPtr, this, Subscriber.getCPtr(p_subscriber), p_subscriber);
  }

  public DataReaderListenerCallBack() {
    this(cpsjavamoduleJNI.new_DataReaderListenerCallBack(), true);
    cpsjavamoduleJNI.DataReaderListenerCallBack_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
