/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class DataReaderListener2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataReaderListener2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataReaderListener2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_DataReaderListener2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataReaderListener2(DataReaderListener p_listener) {
    this(cpsjavamoduleJNI.new_DataReaderListener2__SWIG_0(DataReaderListener.getCPtr(p_listener), p_listener), true);
  }

  public DataReaderListener2() {
    this(cpsjavamoduleJNI.new_DataReaderListener2__SWIG_1(), true);
  }

  public DataReaderListener getListener() {
    return new DataReaderListener(cpsjavamoduleJNI.DataReaderListener2_getListener(swigCPtr, this), true);
  }

  public DataReaderListener getListenerPtr() {
    long cPtr = cpsjavamoduleJNI.DataReaderListener2_getListenerPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new DataReaderListener(cPtr, false);
  }

  public void setCallback(DataReaderListenerCallBack cb) {
    cpsjavamoduleJNI.DataReaderListener2_setCallback(swigCPtr, this, DataReaderListenerCallBack.getCPtr(cb), cb);
  }

  public static void set_callback(DataReaderListenerCallBack value) {
    cpsjavamoduleJNI.DataReaderListener2__callback_set(DataReaderListenerCallBack.getCPtr(value), value);
  }

  public static DataReaderListenerCallBack get_callback() {
    long cPtr = cpsjavamoduleJNI.DataReaderListener2__callback_get();
    return (cPtr == 0) ? null : new DataReaderListenerCallBack(cPtr, false);
  }

}
