/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class DataReader2 extends Entity2 {
  private long swigCPtr;

  protected DataReader2(long cPtr, boolean cMemoryOwn) {
    super(cpsjavamoduleJNI.DataReader2_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataReader2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_DataReader2(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DataReader2(DataReader dataReader) {
    this(cpsjavamoduleJNI.new_DataReader2(DataReader.getCPtr(dataReader), dataReader), true);
  }

  public DataReader getDataReader() {
    long cPtr = cpsjavamoduleJNI.DataReader2_getDataReader(swigCPtr, this);
    return (cPtr == 0) ? null : new DataReader(cPtr, false);
  }

  public ReadCondition2 create_readcondition(long sample_states, long view_states, long instance_states) {
    return new ReadCondition2(cpsjavamoduleJNI.DataReader2_create_readcondition(swigCPtr, this, sample_states, view_states, instance_states), true);
  }

  public QueryCondition2 create_querycondition(long sample_states, long view_states, long instance_states, String query_expression, StringSeq query_parameters) {
    return new QueryCondition2(cpsjavamoduleJNI.DataReader2_create_querycondition(swigCPtr, this, sample_states, view_states, instance_states, query_expression, StringSeq.getCPtr(query_parameters), query_parameters), true);
  }

  public int delete_readcondition(ReadCondition2 condition) {
    return cpsjavamoduleJNI.DataReader2_delete_readcondition(swigCPtr, this, ReadCondition2.getCPtr(condition), condition);
  }

  public int delete_contained_entities() {
    return cpsjavamoduleJNI.DataReader2_delete_contained_entities(swigCPtr, this);
  }

  public int set_qos(DataReaderQos qos) {
    return cpsjavamoduleJNI.DataReader2_set_qos(swigCPtr, this, DataReaderQos.getCPtr(qos), qos);
  }

  public int get_qos(DataReaderQos qos) {
    return cpsjavamoduleJNI.DataReader2_get_qos(swigCPtr, this, DataReaderQos.getCPtr(qos), qos);
  }

  public int set_listener(DataReaderListener2 listener, long mask) {
    return cpsjavamoduleJNI.DataReader2_set_listener(swigCPtr, this, DataReaderListener2.getCPtr(listener), listener, mask);
  }

  public DataReaderListener2 get_listener() {
    return new DataReaderListener2(cpsjavamoduleJNI.DataReader2_get_listener(swigCPtr, this), true);
  }

  public TopicDescription2 get_topicdescription() {
    return new TopicDescription2(cpsjavamoduleJNI.DataReader2_get_topicdescription(swigCPtr, this), true);
  }

  public Subscriber2 get_subscriber() {
    return new Subscriber2(cpsjavamoduleJNI.DataReader2_get_subscriber(swigCPtr, this), true);
  }

  public int get_sample_rejected_status(SampleRejectedStatus status) {
    return cpsjavamoduleJNI.DataReader2_get_sample_rejected_status(swigCPtr, this, SampleRejectedStatus.getCPtr(status), status);
  }

  public int get_liveliness_changed_status(LivelinessChangedStatus status) {
    return cpsjavamoduleJNI.DataReader2_get_liveliness_changed_status(swigCPtr, this, LivelinessChangedStatus.getCPtr(status), status);
  }

  public int get_requested_deadline_missed_status(RequestedDeadlineMissedStatus status) {
    return cpsjavamoduleJNI.DataReader2_get_requested_deadline_missed_status(swigCPtr, this, RequestedDeadlineMissedStatus.getCPtr(status), status);
  }

  public int get_requested_incompatible_qos_status(RequestedIncompatibleQosStatus status) {
    return cpsjavamoduleJNI.DataReader2_get_requested_incompatible_qos_status(swigCPtr, this, RequestedIncompatibleQosStatus.getCPtr(status), status);
  }

  public int get_subscription_matched_status(SubscriptionMatchedStatus status) {
    return cpsjavamoduleJNI.DataReader2_get_subscription_matched_status(swigCPtr, this, SubscriptionMatchedStatus.getCPtr(status), status);
  }

  public int get_sample_lost_status(SampleLostStatus status) {
    return cpsjavamoduleJNI.DataReader2_get_sample_lost_status(swigCPtr, this, SampleLostStatus.getCPtr(status), status);
  }

  public int wait_for_historical_data(Duration_t max_wait) {
    return cpsjavamoduleJNI.DataReader2_wait_for_historical_data(swigCPtr, this, Duration_t.getCPtr(max_wait), max_wait);
  }

  public int get_matched_publications(InstanceHandleSeq publication_handles) {
    return cpsjavamoduleJNI.DataReader2_get_matched_publications(swigCPtr, this, InstanceHandleSeq.getCPtr(publication_handles), publication_handles);
  }

  public int get_matched_publication_data(PublicationBuiltinTopicData publication_data, int publication_handle) {
    return cpsjavamoduleJNI.DataReader2_get_matched_publication_data(swigCPtr, this, PublicationBuiltinTopicData.getCPtr(publication_data), publication_data, publication_handle);
  }

}
