/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class DataWriterListener2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataWriterListener2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataWriterListener2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_DataWriterListener2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataWriterListener2(DataWriterListener p_listener) {
    this(cpsjavamoduleJNI.new_DataWriterListener2__SWIG_0(DataWriterListener.getCPtr(p_listener), p_listener), true);
  }

  public DataWriterListener2() {
    this(cpsjavamoduleJNI.new_DataWriterListener2__SWIG_1(), true);
  }

  public DataWriterListener getListener() {
    return new DataWriterListener(cpsjavamoduleJNI.DataWriterListener2_getListener(swigCPtr, this), true);
  }

  public DataWriterListener getListenerPtr() {
    long cPtr = cpsjavamoduleJNI.DataWriterListener2_getListenerPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new DataWriterListener(cPtr, false);
  }

  public void setCallback(DataWriterListenerCallBack cb) {
    cpsjavamoduleJNI.DataWriterListener2_setCallback(swigCPtr, this, DataWriterListenerCallBack.getCPtr(cb), cb);
  }

  public static void set_callback(DataWriterListenerCallBack value) {
    cpsjavamoduleJNI.DataWriterListener2__callback_set(DataWriterListenerCallBack.getCPtr(value), value);
  }

  public static DataWriterListenerCallBack get_callback() {
    long cPtr = cpsjavamoduleJNI.DataWriterListener2__callback_get();
    return (cPtr == 0) ? null : new DataWriterListenerCallBack(cPtr, false);
  }

}
