/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class DestinationOrderQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DestinationOrderQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DestinationOrderQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_DestinationOrderQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKind(DestinationOrderQosPolicyKind value) {
    cpsjavamoduleJNI.DestinationOrderQosPolicy_kind_set(swigCPtr, this, value.swigValue());
  }

  public DestinationOrderQosPolicyKind getKind() {
    return DestinationOrderQosPolicyKind.swigToEnum(cpsjavamoduleJNI.DestinationOrderQosPolicy_kind_get(swigCPtr, this));
  }

  public DestinationOrderQosPolicy() {
    this(cpsjavamoduleJNI.new_DestinationOrderQosPolicy(), true);
  }

}
