/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public final class DurabilityQosPolicyKind {
  public final static DurabilityQosPolicyKind VOLATILE_DURABILITY_QOS = new DurabilityQosPolicyKind("VOLATILE_DURABILITY_QOS");
  public final static DurabilityQosPolicyKind TRANSIENT_LOCAL_DURABILITY_QOS = new DurabilityQosPolicyKind("TRANSIENT_LOCAL_DURABILITY_QOS");
  public final static DurabilityQosPolicyKind TRANSIENT_DURABILITY_QOS = new DurabilityQosPolicyKind("TRANSIENT_DURABILITY_QOS");
  public final static DurabilityQosPolicyKind PERSISTENT_DURABILITY_QOS = new DurabilityQosPolicyKind("PERSISTENT_DURABILITY_QOS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DurabilityQosPolicyKind swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DurabilityQosPolicyKind.class + " with value " + swigValue);
  }

  private DurabilityQosPolicyKind(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DurabilityQosPolicyKind(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DurabilityQosPolicyKind(String swigName, DurabilityQosPolicyKind swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DurabilityQosPolicyKind[] swigValues = { VOLATILE_DURABILITY_QOS, TRANSIENT_LOCAL_DURABILITY_QOS, TRANSIENT_DURABILITY_QOS, PERSISTENT_DURABILITY_QOS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

