/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class Entity2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Entity2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Entity2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_Entity2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Entity2(Entity entity) {
    this(cpsjavamoduleJNI.new_Entity2(Entity.getCPtr(entity), entity), true);
  }

  public Entity getEntity() {
    long cPtr = cpsjavamoduleJNI.Entity2_getEntity(swigCPtr, this);
    return (cPtr == 0) ? null : new Entity(cPtr, false);
  }

  public int enable() {
    return cpsjavamoduleJNI.Entity2_enable(swigCPtr, this);
  }

  public StatusCondition2 get_statuscondition() {
    return new StatusCondition2(cpsjavamoduleJNI.Entity2_get_statuscondition(swigCPtr, this), true);
  }

  public long get_status_changes() {
    return cpsjavamoduleJNI.Entity2_get_status_changes(swigCPtr, this);
  }

  public int get_instance_handle() {
    return cpsjavamoduleJNI.Entity2_get_instance_handle(swigCPtr, this);
  }

}
