/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class Foo2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Foo2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Foo2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_Foo2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Foo2(SWIGTYPE_p_void data) {
    this(cpsjavamoduleJNI.new_Foo2__SWIG_0(SWIGTYPE_p_void.getCPtr(data)), true);
  }

  public Foo2() {
    this(cpsjavamoduleJNI.new_Foo2__SWIG_1(), true);
  }

  public Foo2(FooTypeSupport2 fooTS1) {
    this(cpsjavamoduleJNI.new_Foo2__SWIG_2(FooTypeSupport2.getCPtr(fooTS1), fooTS1), true);
  }

  public Foo2(FooTypeSupport2 fooTS1, SWIGTYPE_p_void data) {
    this(cpsjavamoduleJNI.new_Foo2__SWIG_3(FooTypeSupport2.getCPtr(fooTS1), fooTS1, SWIGTYPE_p_void.getCPtr(data)), true);
  }

  public void removeFoo() {
    cpsjavamoduleJNI.Foo2_removeFoo(swigCPtr, this);
  }

  public Foo getFoo() {
    long cPtr = cpsjavamoduleJNI.Foo2_getFoo(swigCPtr, this);
    return (cPtr == 0) ? null : new Foo(cPtr, false);
  }

  public FooRet setString(String parameter, String value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setString(swigCPtr, this, parameter, value));
  }

  public FooRet setFloat(String parameter, float value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setFloat(swigCPtr, this, parameter, value));
  }

  public FooRet setInt8(String parameter, byte value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setInt8(swigCPtr, this, parameter, value));
  }

  public FooRet setInt16(String parameter, short value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setInt16(swigCPtr, this, parameter, value));
  }

  public FooRet setInt32(String parameter, int value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setInt32(swigCPtr, this, parameter, value));
  }

  public FooRet setInt64(String parameter, long value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setInt64(swigCPtr, this, parameter, value));
  }

  public FooRet setUint8(String parameter, short value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setUint8(swigCPtr, this, parameter, value));
  }

  public FooRet setUint16(String parameter, int value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setUint16(swigCPtr, this, parameter, value));
  }

  public FooRet setUint32(String parameter, long value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setUint32(swigCPtr, this, parameter, value));
  }

  public FooRet setUint64(String parameter, java.math.BigInteger value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setUint64(swigCPtr, this, parameter, value));
  }

  public FooRet setDouble(String parameter, double value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setDouble(swigCPtr, this, parameter, value));
  }

  public FooRet setBoolean(String parameter, boolean value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setBoolean(swigCPtr, this, parameter, value));
  }

  public FooRet setByte(String parameter, byte value) {
    return FooRet.swigToEnum(cpsjavamoduleJNI.Foo2_setByte(swigCPtr, this, parameter, value));
  }

  public String getString(String parameter) {
    return cpsjavamoduleJNI.Foo2_getString(swigCPtr, this, parameter);
  }

  public float getFloat(String parameter) {
    return cpsjavamoduleJNI.Foo2_getFloat(swigCPtr, this, parameter);
  }

  public byte getInt8(String parameter) {
    return cpsjavamoduleJNI.Foo2_getInt8(swigCPtr, this, parameter);
  }

  public short getInt16(String parameter) {
    return cpsjavamoduleJNI.Foo2_getInt16(swigCPtr, this, parameter);
  }

  public int getInt32(String parameter) {
    return cpsjavamoduleJNI.Foo2_getInt32(swigCPtr, this, parameter);
  }

  public long getInt64(String parameter) {
    return cpsjavamoduleJNI.Foo2_getInt64(swigCPtr, this, parameter);
  }

  public short getUint8(String parameter) {
    return cpsjavamoduleJNI.Foo2_getUint8(swigCPtr, this, parameter);
  }

  public int getUint16(String parameter) {
    return cpsjavamoduleJNI.Foo2_getUint16(swigCPtr, this, parameter);
  }

  public long getUint32(String parameter) {
    return cpsjavamoduleJNI.Foo2_getUint32(swigCPtr, this, parameter);
  }

  public java.math.BigInteger getUint64(String parameter) {
    return cpsjavamoduleJNI.Foo2_getUint64(swigCPtr, this, parameter);
  }

  public double getDouble(String parameter) {
    return cpsjavamoduleJNI.Foo2_getDouble(swigCPtr, this, parameter);
  }

  public boolean getBoolean(String parameter) {
    return cpsjavamoduleJNI.Foo2_getBoolean(swigCPtr, this, parameter);
  }

  public byte getByte(String parameter) {
    return cpsjavamoduleJNI.Foo2_getByte(swigCPtr, this, parameter);
  }

}
