/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class FooTypeSupport {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FooTypeSupport(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FooTypeSupport obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_FooTypeSupport(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI_size(int value) {
    cpsjavamoduleJNI.FooTypeSupport_i_size_set(swigCPtr, this, value);
  }

  public int getI_size() {
    return cpsjavamoduleJNI.FooTypeSupport_i_size_get(swigCPtr, this);
  }

  public void setI_parameters(int value) {
    cpsjavamoduleJNI.FooTypeSupport_i_parameters_set(swigCPtr, this, value);
  }

  public int getI_parameters() {
    return cpsjavamoduleJNI.FooTypeSupport_i_parameters_get(swigCPtr, this);
  }

  public FooTypeSupport() {
    this(cpsjavamoduleJNI.new_FooTypeSupport(), true);
  }

}
