/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class FooTypeSupport2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FooTypeSupport2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FooTypeSupport2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_FooTypeSupport2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FooTypeSupport2() {
    this(cpsjavamoduleJNI.new_FooTypeSupport2(), true);
  }

  public FooTypeSupport getFooTypeSupport() {
    long cPtr = cpsjavamoduleJNI.FooTypeSupport2_getFooTypeSupport(swigCPtr, this);
    return (cPtr == 0) ? null : new FooTypeSupport(cPtr, false);
  }

  public int register_type(DomainParticipant2 participant, String type_name) {
    return cpsjavamoduleJNI.FooTypeSupport2_register_type(swigCPtr, this, DomainParticipant2.getCPtr(participant), participant, type_name);
  }

  public String get_type_name() {
    return cpsjavamoduleJNI.FooTypeSupport2_get_type_name(swigCPtr, this);
  }

  public boolean insert_parameter(String parameter_name, SUPPORT_TYPE type, boolean is_key) {
    return cpsjavamoduleJNI.FooTypeSupport2_insert_parameter__SWIG_0(swigCPtr, this, parameter_name, type.swigValue(), is_key);
  }

  public boolean insert_parameter(String parameter_name, SUPPORT_TYPE type) {
    return cpsjavamoduleJNI.FooTypeSupport2_insert_parameter__SWIG_1(swigCPtr, this, parameter_name, type.swigValue());
  }

  public boolean insert_parameter_struct(String parameter_name, int size, boolean is_key) {
    return cpsjavamoduleJNI.FooTypeSupport2_insert_parameter_struct__SWIG_0(swigCPtr, this, parameter_name, size, is_key);
  }

  public boolean insert_parameter_struct(String parameter_name, int size) {
    return cpsjavamoduleJNI.FooTypeSupport2_insert_parameter_struct__SWIG_1(swigCPtr, this, parameter_name, size);
  }

  public void setFootypeSize(int size) {
    cpsjavamoduleJNI.FooTypeSupport2_setFootypeSize(swigCPtr, this, size);
  }

}
