/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class GroupDataQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GroupDataQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GroupDataQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_GroupDataQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(StringSeq value) {
    cpsjavamoduleJNI.GroupDataQosPolicy_value_set(swigCPtr, this, StringSeq.getCPtr(value), value);
  }

  public StringSeq getValue() {
    long cPtr = cpsjavamoduleJNI.GroupDataQosPolicy_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringSeq(cPtr, false);
  }

  public GroupDataQosPolicy() {
    this(cpsjavamoduleJNI.new_GroupDataQosPolicy(), true);
  }

}
