/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class HistoryQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected HistoryQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HistoryQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_HistoryQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKind(HistoryQosPolicyKind value) {
    cpsjavamoduleJNI.HistoryQosPolicy_kind_set(swigCPtr, this, value.swigValue());
  }

  public HistoryQosPolicyKind getKind() {
    return HistoryQosPolicyKind.swigToEnum(cpsjavamoduleJNI.HistoryQosPolicy_kind_get(swigCPtr, this));
  }

  public void setDepth(int value) {
    cpsjavamoduleJNI.HistoryQosPolicy_depth_set(swigCPtr, this, value);
  }

  public int getDepth() {
    return cpsjavamoduleJNI.HistoryQosPolicy_depth_get(swigCPtr, this);
  }

  public HistoryQosPolicy() {
    this(cpsjavamoduleJNI.new_HistoryQosPolicy(), true);
  }

}
