/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class InstanceHandleSeq {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected InstanceHandleSeq(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InstanceHandleSeq obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_InstanceHandleSeq(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI_seq(int value) {
    cpsjavamoduleJNI.InstanceHandleSeq_i_seq_set(swigCPtr, this, value);
  }

  public int getI_seq() {
    return cpsjavamoduleJNI.InstanceHandleSeq_i_seq_get(swigCPtr, this);
  }

  public void setPp_instancehandle(SWIGTYPE_p_p_long value) {
    cpsjavamoduleJNI.InstanceHandleSeq_pp_instancehandle_set(swigCPtr, this, SWIGTYPE_p_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_p_long getPp_instancehandle() {
    long cPtr = cpsjavamoduleJNI.InstanceHandleSeq_pp_instancehandle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_long(cPtr, false);
  }

  public InstanceHandleSeq() {
    this(cpsjavamoduleJNI.new_InstanceHandleSeq(), true);
  }

}
