/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class LifespanQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LifespanQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LifespanQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_LifespanQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDuration(Duration_t value) {
    cpsjavamoduleJNI.LifespanQosPolicy_duration_set(swigCPtr, this, Duration_t.getCPtr(value), value);
  }

  public Duration_t getDuration() {
    long cPtr = cpsjavamoduleJNI.LifespanQosPolicy_duration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Duration_t(cPtr, false);
  }

  public LifespanQosPolicy() {
    this(cpsjavamoduleJNI.new_LifespanQosPolicy(), true);
  }

}
