/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class LivelinessChangedStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LivelinessChangedStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LivelinessChangedStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_LivelinessChangedStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAlive_count(int value) {
    cpsjavamoduleJNI.LivelinessChangedStatus_alive_count_set(swigCPtr, this, value);
  }

  public int getAlive_count() {
    return cpsjavamoduleJNI.LivelinessChangedStatus_alive_count_get(swigCPtr, this);
  }

  public void setNot_alive_count(int value) {
    cpsjavamoduleJNI.LivelinessChangedStatus_not_alive_count_set(swigCPtr, this, value);
  }

  public int getNot_alive_count() {
    return cpsjavamoduleJNI.LivelinessChangedStatus_not_alive_count_get(swigCPtr, this);
  }

  public void setAlive_count_change(int value) {
    cpsjavamoduleJNI.LivelinessChangedStatus_alive_count_change_set(swigCPtr, this, value);
  }

  public int getAlive_count_change() {
    return cpsjavamoduleJNI.LivelinessChangedStatus_alive_count_change_get(swigCPtr, this);
  }

  public void setNot_alive_count_change(int value) {
    cpsjavamoduleJNI.LivelinessChangedStatus_not_alive_count_change_set(swigCPtr, this, value);
  }

  public int getNot_alive_count_change() {
    return cpsjavamoduleJNI.LivelinessChangedStatus_not_alive_count_change_get(swigCPtr, this);
  }

  public void setLast_publication_handle(int value) {
    cpsjavamoduleJNI.LivelinessChangedStatus_last_publication_handle_set(swigCPtr, this, value);
  }

  public int getLast_publication_handle() {
    return cpsjavamoduleJNI.LivelinessChangedStatus_last_publication_handle_get(swigCPtr, this);
  }

  public LivelinessChangedStatus() {
    this(cpsjavamoduleJNI.new_LivelinessChangedStatus(), true);
  }

}
