/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class message_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected message_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(message_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_message_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI_datasize(int value) {
    cpsjavamoduleJNI.message_t_i_datasize_set(swigCPtr, this, value);
  }

  public int getI_datasize() {
    return cpsjavamoduleJNI.message_t_i_datasize_get(swigCPtr, this);
  }

  public void setV_data(SWIGTYPE_p_void value) {
    cpsjavamoduleJNI.message_t_v_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getV_data() {
    long cPtr = cpsjavamoduleJNI.message_t_v_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public message_t() {
    this(cpsjavamoduleJNI.new_message_t(), true);
  }

}
