/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class Message2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Message2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Message2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_Message2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Message2() {
    this(cpsjavamoduleJNI.new_Message2__SWIG_0(), true);
  }

  public Message2(message_t message) {
    this(cpsjavamoduleJNI.new_Message2__SWIG_1(message_t.getCPtr(message), message), true);
  }

  public void removeMessage() {
    cpsjavamoduleJNI.Message2_removeMessage(swigCPtr, this);
  }

  public SWIGTYPE_p_void getValue() {
    long cPtr = cpsjavamoduleJNI.Message2_getValue(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

}
