/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class MultiTopic2 extends Entity2 {
  private long swigCPtr;

  protected MultiTopic2(long cPtr, boolean cMemoryOwn) {
    super(cpsjavamoduleJNI.MultiTopic2_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiTopic2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_MultiTopic2(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MultiTopic2(MultiTopic topic) {
    this(cpsjavamoduleJNI.new_MultiTopic2(MultiTopic.getCPtr(topic), topic), true);
  }

  public MultiTopic getMultiTopic() {
    long cPtr = cpsjavamoduleJNI.MultiTopic2_getMultiTopic(swigCPtr, this);
    return (cPtr == 0) ? null : new MultiTopic(cPtr, false);
  }

  public String get_subscription_expression() {
    return cpsjavamoduleJNI.MultiTopic2_get_subscription_expression(swigCPtr, this);
  }

  public int get_expression_parameters(StringSeq expression_parameters) {
    return cpsjavamoduleJNI.MultiTopic2_get_expression_parameters(swigCPtr, this, StringSeq.getCPtr(expression_parameters), expression_parameters);
  }

  public int set_expression_parameters(StringSeq expression_parameters) {
    return cpsjavamoduleJNI.MultiTopic2_set_expression_parameters(swigCPtr, this, StringSeq.getCPtr(expression_parameters), expression_parameters);
  }

}
