/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class OwnershipQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OwnershipQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OwnershipQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_OwnershipQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKind(OwnershipQosPolicyKind value) {
    cpsjavamoduleJNI.OwnershipQosPolicy_kind_set(swigCPtr, this, value.swigValue());
  }

  public OwnershipQosPolicyKind getKind() {
    return OwnershipQosPolicyKind.swigToEnum(cpsjavamoduleJNI.OwnershipQosPolicy_kind_get(swigCPtr, this));
  }

  public OwnershipQosPolicy() {
    this(cpsjavamoduleJNI.new_OwnershipQosPolicy(), true);
  }

}
