/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class OwnershipStrengthQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OwnershipStrengthQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OwnershipStrengthQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_OwnershipStrengthQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(int value) {
    cpsjavamoduleJNI.OwnershipStrengthQosPolicy_value_set(swigCPtr, this, value);
  }

  public int getValue() {
    return cpsjavamoduleJNI.OwnershipStrengthQosPolicy_value_get(swigCPtr, this);
  }

  public OwnershipStrengthQosPolicy() {
    this(cpsjavamoduleJNI.new_OwnershipStrengthQosPolicy(), true);
  }

}
