/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class PresentationQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PresentationQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PresentationQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_PresentationQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAccess_scope(PresentationQosPolicyAccessScopeKind value) {
    cpsjavamoduleJNI.PresentationQosPolicy_access_scope_set(swigCPtr, this, value.swigValue());
  }

  public PresentationQosPolicyAccessScopeKind getAccess_scope() {
    return PresentationQosPolicyAccessScopeKind.swigToEnum(cpsjavamoduleJNI.PresentationQosPolicy_access_scope_get(swigCPtr, this));
  }

  public void setCoherent_access(boolean value) {
    cpsjavamoduleJNI.PresentationQosPolicy_coherent_access_set(swigCPtr, this, value);
  }

  public boolean getCoherent_access() {
    return cpsjavamoduleJNI.PresentationQosPolicy_coherent_access_get(swigCPtr, this);
  }

  public void setOrdered_access(boolean value) {
    cpsjavamoduleJNI.PresentationQosPolicy_ordered_access_set(swigCPtr, this, value);
  }

  public boolean getOrdered_access() {
    return cpsjavamoduleJNI.PresentationQosPolicy_ordered_access_get(swigCPtr, this);
  }

  public PresentationQosPolicy() {
    this(cpsjavamoduleJNI.new_PresentationQosPolicy(), true);
  }

}
