/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class PublisherQos {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PublisherQos(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublisherQos obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_PublisherQos(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPresentation(PresentationQosPolicy value) {
    cpsjavamoduleJNI.PublisherQos_presentation_set(swigCPtr, this, PresentationQosPolicy.getCPtr(value), value);
  }

  public PresentationQosPolicy getPresentation() {
    long cPtr = cpsjavamoduleJNI.PublisherQos_presentation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PresentationQosPolicy(cPtr, false);
  }

  public void setPartition(PartitionQosPolicy value) {
    cpsjavamoduleJNI.PublisherQos_partition_set(swigCPtr, this, PartitionQosPolicy.getCPtr(value), value);
  }

  public PartitionQosPolicy getPartition() {
    long cPtr = cpsjavamoduleJNI.PublisherQos_partition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PartitionQosPolicy(cPtr, false);
  }

  public void setGroup_data(GroupDataQosPolicy value) {
    cpsjavamoduleJNI.PublisherQos_group_data_set(swigCPtr, this, GroupDataQosPolicy.getCPtr(value), value);
  }

  public GroupDataQosPolicy getGroup_data() {
    long cPtr = cpsjavamoduleJNI.PublisherQos_group_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GroupDataQosPolicy(cPtr, false);
  }

  public void setEntity_factory(EntityFactoryQosPolicy value) {
    cpsjavamoduleJNI.PublisherQos_entity_factory_set(swigCPtr, this, EntityFactoryQosPolicy.getCPtr(value), value);
  }

  public EntityFactoryQosPolicy getEntity_factory() {
    long cPtr = cpsjavamoduleJNI.PublisherQos_entity_factory_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EntityFactoryQosPolicy(cPtr, false);
  }

  public PublisherQos() {
    this(cpsjavamoduleJNI.new_PublisherQos(), true);
  }

}
