/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class PublicationBuiltinTopicData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PublicationBuiltinTopicData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublicationBuiltinTopicData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_PublicationBuiltinTopicData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKey(BuiltinTopicKey_t value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_key_set(swigCPtr, this, BuiltinTopicKey_t.getCPtr(value), value);
  }

  public BuiltinTopicKey_t getKey() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_key_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BuiltinTopicKey_t(cPtr, false);
  }

  public void setParticipant_key(BuiltinTopicKey_t value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_participant_key_set(swigCPtr, this, BuiltinTopicKey_t.getCPtr(value), value);
  }

  public BuiltinTopicKey_t getParticipant_key() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_participant_key_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BuiltinTopicKey_t(cPtr, false);
  }

  public void setTopic_name(String value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_topic_name_set(swigCPtr, this, value);
  }

  public String getTopic_name() {
    return cpsjavamoduleJNI.PublicationBuiltinTopicData_topic_name_get(swigCPtr, this);
  }

  public void setType_name(String value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_type_name_set(swigCPtr, this, value);
  }

  public String getType_name() {
    return cpsjavamoduleJNI.PublicationBuiltinTopicData_type_name_get(swigCPtr, this);
  }

  public void setDurability(DurabilityQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_durability_set(swigCPtr, this, DurabilityQosPolicy.getCPtr(value), value);
  }

  public DurabilityQosPolicy getDurability() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_durability_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DurabilityQosPolicy(cPtr, false);
  }

  public void setDurability_service(DurabilityServiceQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_durability_service_set(swigCPtr, this, DurabilityServiceQosPolicy.getCPtr(value), value);
  }

  public DurabilityServiceQosPolicy getDurability_service() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_durability_service_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DurabilityServiceQosPolicy(cPtr, false);
  }

  public void setDeadline(DeadlineQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_deadline_set(swigCPtr, this, DeadlineQosPolicy.getCPtr(value), value);
  }

  public DeadlineQosPolicy getDeadline() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_deadline_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DeadlineQosPolicy(cPtr, false);
  }

  public void setLatency_budget(LatencyBudgetQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_latency_budget_set(swigCPtr, this, LatencyBudgetQosPolicy.getCPtr(value), value);
  }

  public LatencyBudgetQosPolicy getLatency_budget() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_latency_budget_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LatencyBudgetQosPolicy(cPtr, false);
  }

  public void setLiveliness(LivelinessQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_liveliness_set(swigCPtr, this, LivelinessQosPolicy.getCPtr(value), value);
  }

  public LivelinessQosPolicy getLiveliness() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_liveliness_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LivelinessQosPolicy(cPtr, false);
  }

  public void setReliability(ReliabilityQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_reliability_set(swigCPtr, this, ReliabilityQosPolicy.getCPtr(value), value);
  }

  public ReliabilityQosPolicy getReliability() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_reliability_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ReliabilityQosPolicy(cPtr, false);
  }

  public void setLifespan(LifespanQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_lifespan_set(swigCPtr, this, LifespanQosPolicy.getCPtr(value), value);
  }

  public LifespanQosPolicy getLifespan() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_lifespan_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LifespanQosPolicy(cPtr, false);
  }

  public void setUser_data(UserDataQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_user_data_set(swigCPtr, this, UserDataQosPolicy.getCPtr(value), value);
  }

  public UserDataQosPolicy getUser_data() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_user_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UserDataQosPolicy(cPtr, false);
  }

  public void setOwnership(OwnershipQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_ownership_set(swigCPtr, this, OwnershipQosPolicy.getCPtr(value), value);
  }

  public OwnershipQosPolicy getOwnership() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_ownership_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OwnershipQosPolicy(cPtr, false);
  }

  public void setOwnership_strength(OwnershipStrengthQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_ownership_strength_set(swigCPtr, this, OwnershipStrengthQosPolicy.getCPtr(value), value);
  }

  public OwnershipStrengthQosPolicy getOwnership_strength() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_ownership_strength_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OwnershipStrengthQosPolicy(cPtr, false);
  }

  public void setDestination_order(DestinationOrderQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_destination_order_set(swigCPtr, this, DestinationOrderQosPolicy.getCPtr(value), value);
  }

  public DestinationOrderQosPolicy getDestination_order() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_destination_order_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DestinationOrderQosPolicy(cPtr, false);
  }

  public void setPresentation(PresentationQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_presentation_set(swigCPtr, this, PresentationQosPolicy.getCPtr(value), value);
  }

  public PresentationQosPolicy getPresentation() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_presentation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PresentationQosPolicy(cPtr, false);
  }

  public void setPartition(PartitionQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_partition_set(swigCPtr, this, PartitionQosPolicy.getCPtr(value), value);
  }

  public PartitionQosPolicy getPartition() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_partition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PartitionQosPolicy(cPtr, false);
  }

  public void setTopic_data(TopicDataQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_topic_data_set(swigCPtr, this, TopicDataQosPolicy.getCPtr(value), value);
  }

  public TopicDataQosPolicy getTopic_data() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_topic_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TopicDataQosPolicy(cPtr, false);
  }

  public void setGroup_data(GroupDataQosPolicy value) {
    cpsjavamoduleJNI.PublicationBuiltinTopicData_group_data_set(swigCPtr, this, GroupDataQosPolicy.getCPtr(value), value);
  }

  public GroupDataQosPolicy getGroup_data() {
    long cPtr = cpsjavamoduleJNI.PublicationBuiltinTopicData_group_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GroupDataQosPolicy(cPtr, false);
  }

  public PublicationBuiltinTopicData() {
    this(cpsjavamoduleJNI.new_PublicationBuiltinTopicData(), true);
  }

}
