/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class PublisherListenerCallBack {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PublisherListenerCallBack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublisherListenerCallBack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_PublisherListenerCallBack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    cpsjavamoduleJNI.PublisherListenerCallBack_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    cpsjavamoduleJNI.PublisherListenerCallBack_change_ownership(this, swigCPtr, true);
  }

  public void on_offered_deadline_missed(DataWriter writer, OfferedDeadlineMissedStatus status) {
    cpsjavamoduleJNI.PublisherListenerCallBack_on_offered_deadline_missed(swigCPtr, this, DataWriter.getCPtr(writer), writer, OfferedDeadlineMissedStatus.getCPtr(status), status);
  }

  public void on_offered_incompatible_qos(DataWriter writer, OfferedIncompatibleQosStatus status) {
    cpsjavamoduleJNI.PublisherListenerCallBack_on_offered_incompatible_qos(swigCPtr, this, DataWriter.getCPtr(writer), writer, OfferedIncompatibleQosStatus.getCPtr(status), status);
  }

  public void on_liveliness_lost(DataWriter writer, LivelinessLostStatus status) {
    cpsjavamoduleJNI.PublisherListenerCallBack_on_liveliness_lost(swigCPtr, this, DataWriter.getCPtr(writer), writer, LivelinessLostStatus.getCPtr(status), status);
  }

  public void on_publication_matched(DataWriter writer, PublicationMatchedStatus status) {
    cpsjavamoduleJNI.PublisherListenerCallBack_on_publication_matched(swigCPtr, this, DataWriter.getCPtr(writer), writer, PublicationMatchedStatus.getCPtr(status), status);
  }

  public PublisherListenerCallBack() {
    this(cpsjavamoduleJNI.new_PublisherListenerCallBack(), true);
    cpsjavamoduleJNI.PublisherListenerCallBack_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
