/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class Publisher {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Publisher(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Publisher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_Publisher(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI_entity_type(int value) {
    cpsjavamoduleJNI.Publisher_i_entity_type_set(swigCPtr, this, value);
  }

  public int getI_entity_type() {
    return cpsjavamoduleJNI.Publisher_i_entity_type_get(swigCPtr, this);
  }

  public Publisher() {
    this(cpsjavamoduleJNI.new_Publisher(), true);
  }

}
