/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class ReadCondition2 extends Condition2 {
  private long swigCPtr;

  protected ReadCondition2(long cPtr, boolean cMemoryOwn) {
    super(cpsjavamoduleJNI.ReadCondition2_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReadCondition2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_ReadCondition2(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ReadCondition2(ReadCondition condition) {
    this(cpsjavamoduleJNI.new_ReadCondition2(ReadCondition.getCPtr(condition), condition), true);
  }

  public ReadCondition getReadCondition() {
    long cPtr = cpsjavamoduleJNI.ReadCondition2_getReadCondition(swigCPtr, this);
    return (cPtr == 0) ? null : new ReadCondition(cPtr, false);
  }

  public long get_sample_state_mask() {
    return cpsjavamoduleJNI.ReadCondition2_get_sample_state_mask(swigCPtr, this);
  }

  public long get_view_state_mask() {
    return cpsjavamoduleJNI.ReadCondition2_get_view_state_mask(swigCPtr, this);
  }

  public long get_instance_state_mask() {
    return cpsjavamoduleJNI.ReadCondition2_get_instance_state_mask(swigCPtr, this);
  }

  public DataReader2 get_datareader() {
    return new DataReader2(cpsjavamoduleJNI.ReadCondition2_get_datareader(swigCPtr, this), true);
  }

}
