/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class ReliabilityQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ReliabilityQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReliabilityQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_ReliabilityQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKind(ReliabilityQosPolicyKind value) {
    cpsjavamoduleJNI.ReliabilityQosPolicy_kind_set(swigCPtr, this, value.swigValue());
  }

  public ReliabilityQosPolicyKind getKind() {
    return ReliabilityQosPolicyKind.swigToEnum(cpsjavamoduleJNI.ReliabilityQosPolicy_kind_get(swigCPtr, this));
  }

  public void setMax_blocking_time(Duration_t value) {
    cpsjavamoduleJNI.ReliabilityQosPolicy_max_blocking_time_set(swigCPtr, this, Duration_t.getCPtr(value), value);
  }

  public Duration_t getMax_blocking_time() {
    long cPtr = cpsjavamoduleJNI.ReliabilityQosPolicy_max_blocking_time_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Duration_t(cPtr, false);
  }

  public ReliabilityQosPolicy() {
    this(cpsjavamoduleJNI.new_ReliabilityQosPolicy(), true);
  }

}
