/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class RequestedIncompatibleQosStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RequestedIncompatibleQosStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RequestedIncompatibleQosStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_RequestedIncompatibleQosStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTotal_count(int value) {
    cpsjavamoduleJNI.RequestedIncompatibleQosStatus_total_count_set(swigCPtr, this, value);
  }

  public int getTotal_count() {
    return cpsjavamoduleJNI.RequestedIncompatibleQosStatus_total_count_get(swigCPtr, this);
  }

  public void setTotal_count_change(int value) {
    cpsjavamoduleJNI.RequestedIncompatibleQosStatus_total_count_change_set(swigCPtr, this, value);
  }

  public int getTotal_count_change() {
    return cpsjavamoduleJNI.RequestedIncompatibleQosStatus_total_count_change_get(swigCPtr, this);
  }

  public void setLast_policy_id(int value) {
    cpsjavamoduleJNI.RequestedIncompatibleQosStatus_last_policy_id_set(swigCPtr, this, value);
  }

  public int getLast_policy_id() {
    return cpsjavamoduleJNI.RequestedIncompatibleQosStatus_last_policy_id_get(swigCPtr, this);
  }

  public void setPolicies(QosPolicyCount value) {
    cpsjavamoduleJNI.RequestedIncompatibleQosStatus_policies_set(swigCPtr, this, QosPolicyCount.getCPtr(value), value);
  }

  public QosPolicyCount getPolicies() {
    long cPtr = cpsjavamoduleJNI.RequestedIncompatibleQosStatus_policies_get(swigCPtr, this);
    return (cPtr == 0) ? null : new QosPolicyCount(cPtr, false);
  }

  public RequestedIncompatibleQosStatus() {
    this(cpsjavamoduleJNI.new_RequestedIncompatibleQosStatus(), true);
  }

}
