/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class ResourceLimitsQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ResourceLimitsQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResourceLimitsQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_ResourceLimitsQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMax_samples(int value) {
    cpsjavamoduleJNI.ResourceLimitsQosPolicy_max_samples_set(swigCPtr, this, value);
  }

  public int getMax_samples() {
    return cpsjavamoduleJNI.ResourceLimitsQosPolicy_max_samples_get(swigCPtr, this);
  }

  public void setMax_instances(int value) {
    cpsjavamoduleJNI.ResourceLimitsQosPolicy_max_instances_set(swigCPtr, this, value);
  }

  public int getMax_instances() {
    return cpsjavamoduleJNI.ResourceLimitsQosPolicy_max_instances_get(swigCPtr, this);
  }

  public void setMax_samples_per_instance(int value) {
    cpsjavamoduleJNI.ResourceLimitsQosPolicy_max_samples_per_instance_set(swigCPtr, this, value);
  }

  public int getMax_samples_per_instance() {
    return cpsjavamoduleJNI.ResourceLimitsQosPolicy_max_samples_per_instance_get(swigCPtr, this);
  }

  public ResourceLimitsQosPolicy() {
    this(cpsjavamoduleJNI.new_ResourceLimitsQosPolicy(), true);
  }

}
