/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class SampleLostStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SampleLostStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SampleLostStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_SampleLostStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTotal_count(int value) {
    cpsjavamoduleJNI.SampleLostStatus_total_count_set(swigCPtr, this, value);
  }

  public int getTotal_count() {
    return cpsjavamoduleJNI.SampleLostStatus_total_count_get(swigCPtr, this);
  }

  public void setTotal_count_change(int value) {
    cpsjavamoduleJNI.SampleLostStatus_total_count_change_set(swigCPtr, this, value);
  }

  public int getTotal_count_change() {
    return cpsjavamoduleJNI.SampleLostStatus_total_count_change_get(swigCPtr, this);
  }

  public SampleLostStatus() {
    this(cpsjavamoduleJNI.new_SampleLostStatus(), true);
  }

}
