/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class SampleInfo2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SampleInfo2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SampleInfo2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_SampleInfo2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SampleInfo2() {
    this(cpsjavamoduleJNI.new_SampleInfo2(), true);
  }

  public SampleInfo getSampleInfo() {
    long cPtr = cpsjavamoduleJNI.SampleInfo2_getSampleInfo(swigCPtr, this);
    return (cPtr == 0) ? null : new SampleInfo(cPtr, false);
  }

}
