/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class SampleInfoSeq {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SampleInfoSeq(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SampleInfoSeq obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_SampleInfoSeq(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI_seq(int value) {
    cpsjavamoduleJNI.SampleInfoSeq_i_seq_set(swigCPtr, this, value);
  }

  public int getI_seq() {
    return cpsjavamoduleJNI.SampleInfoSeq_i_seq_get(swigCPtr, this);
  }

  public void setPp_sample_infos(SWIGTYPE_p_p_SampleInfo value) {
    cpsjavamoduleJNI.SampleInfoSeq_pp_sample_infos_set(swigCPtr, this, SWIGTYPE_p_p_SampleInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p_SampleInfo getPp_sample_infos() {
    long cPtr = cpsjavamoduleJNI.SampleInfoSeq_pp_sample_infos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_SampleInfo(cPtr, false);
  }

  public SampleInfoSeq() {
    this(cpsjavamoduleJNI.new_SampleInfoSeq(), true);
  }

}
