/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class SampleInfoSeq2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SampleInfoSeq2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SampleInfoSeq2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_SampleInfoSeq2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SampleInfoSeq2() {
    this(cpsjavamoduleJNI.new_SampleInfoSeq2(), true);
  }

  public SampleInfoSeq getSampleInfoSeq() {
    return new SampleInfoSeq(cpsjavamoduleJNI.SampleInfoSeq2_getSampleInfoSeq(swigCPtr, this), true);
  }

  public SampleInfoSeq getSampleInfoSeqPtr() {
    long cPtr = cpsjavamoduleJNI.SampleInfoSeq2_getSampleInfoSeqPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new SampleInfoSeq(cPtr, false);
  }

}
