/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public final class SampleRejectedStatusKind {
  public final static SampleRejectedStatusKind NOT_REJECTED = new SampleRejectedStatusKind("NOT_REJECTED");
  public final static SampleRejectedStatusKind REJECTED_BY_INSTANCES_LIMIT = new SampleRejectedStatusKind("REJECTED_BY_INSTANCES_LIMIT");
  public final static SampleRejectedStatusKind REJECTED_BY_SAMPLES_LIMIT = new SampleRejectedStatusKind("REJECTED_BY_SAMPLES_LIMIT");
  public final static SampleRejectedStatusKind REJECTED_BY_SAMPLES_PER_INSTANCE_LIMIT = new SampleRejectedStatusKind("REJECTED_BY_SAMPLES_PER_INSTANCE_LIMIT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SampleRejectedStatusKind swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SampleRejectedStatusKind.class + " with value " + swigValue);
  }

  private SampleRejectedStatusKind(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SampleRejectedStatusKind(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SampleRejectedStatusKind(String swigName, SampleRejectedStatusKind swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SampleRejectedStatusKind[] swigValues = { NOT_REJECTED, REJECTED_BY_INSTANCES_LIMIT, REJECTED_BY_SAMPLES_LIMIT, REJECTED_BY_SAMPLES_PER_INSTANCE_LIMIT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

