/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class SampleInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SampleInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SampleInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_SampleInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSample_state(long value) {
    cpsjavamoduleJNI.SampleInfo_sample_state_set(swigCPtr, this, value);
  }

  public long getSample_state() {
    return cpsjavamoduleJNI.SampleInfo_sample_state_get(swigCPtr, this);
  }

  public void setView_state(long value) {
    cpsjavamoduleJNI.SampleInfo_view_state_set(swigCPtr, this, value);
  }

  public long getView_state() {
    return cpsjavamoduleJNI.SampleInfo_view_state_get(swigCPtr, this);
  }

  public void setInstance_state(long value) {
    cpsjavamoduleJNI.SampleInfo_instance_state_set(swigCPtr, this, value);
  }

  public long getInstance_state() {
    return cpsjavamoduleJNI.SampleInfo_instance_state_get(swigCPtr, this);
  }

  public void setSource_timestamp(Time_t value) {
    cpsjavamoduleJNI.SampleInfo_source_timestamp_set(swigCPtr, this, Time_t.getCPtr(value), value);
  }

  public Time_t getSource_timestamp() {
    long cPtr = cpsjavamoduleJNI.SampleInfo_source_timestamp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Time_t(cPtr, false);
  }

  public void setInstance_handle(int value) {
    cpsjavamoduleJNI.SampleInfo_instance_handle_set(swigCPtr, this, value);
  }

  public int getInstance_handle() {
    return cpsjavamoduleJNI.SampleInfo_instance_handle_get(swigCPtr, this);
  }

  public void setPublication_handle(int value) {
    cpsjavamoduleJNI.SampleInfo_publication_handle_set(swigCPtr, this, value);
  }

  public int getPublication_handle() {
    return cpsjavamoduleJNI.SampleInfo_publication_handle_get(swigCPtr, this);
  }

  public void setDisposed_generation_count(int value) {
    cpsjavamoduleJNI.SampleInfo_disposed_generation_count_set(swigCPtr, this, value);
  }

  public int getDisposed_generation_count() {
    return cpsjavamoduleJNI.SampleInfo_disposed_generation_count_get(swigCPtr, this);
  }

  public void setNo_writers_generation_count(int value) {
    cpsjavamoduleJNI.SampleInfo_no_writers_generation_count_set(swigCPtr, this, value);
  }

  public int getNo_writers_generation_count() {
    return cpsjavamoduleJNI.SampleInfo_no_writers_generation_count_get(swigCPtr, this);
  }

  public void setSample_rank(int value) {
    cpsjavamoduleJNI.SampleInfo_sample_rank_set(swigCPtr, this, value);
  }

  public int getSample_rank() {
    return cpsjavamoduleJNI.SampleInfo_sample_rank_get(swigCPtr, this);
  }

  public void setGeneration_rank(int value) {
    cpsjavamoduleJNI.SampleInfo_generation_rank_set(swigCPtr, this, value);
  }

  public int getGeneration_rank() {
    return cpsjavamoduleJNI.SampleInfo_generation_rank_get(swigCPtr, this);
  }

  public void setAbsolute_generation_rank(int value) {
    cpsjavamoduleJNI.SampleInfo_absolute_generation_rank_set(swigCPtr, this, value);
  }

  public int getAbsolute_generation_rank() {
    return cpsjavamoduleJNI.SampleInfo_absolute_generation_rank_get(swigCPtr, this);
  }

  public void setValid_data(boolean value) {
    cpsjavamoduleJNI.SampleInfo_valid_data_set(swigCPtr, this, value);
  }

  public boolean getValid_data() {
    return cpsjavamoduleJNI.SampleInfo_valid_data_get(swigCPtr, this);
  }

  public void setDisposed_timestamp(Time_t value) {
    cpsjavamoduleJNI.SampleInfo_disposed_timestamp_set(swigCPtr, this, Time_t.getCPtr(value), value);
  }

  public Time_t getDisposed_timestamp() {
    long cPtr = cpsjavamoduleJNI.SampleInfo_disposed_timestamp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Time_t(cPtr, false);
  }

  public SampleInfo() {
    this(cpsjavamoduleJNI.new_SampleInfo(), true);
  }

}
