/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class StatusCondition2 extends Condition2 {
  private long swigCPtr;

  protected StatusCondition2(long cPtr, boolean cMemoryOwn) {
    super(cpsjavamoduleJNI.StatusCondition2_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusCondition2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_StatusCondition2(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StatusCondition2(StatusCondition condition) {
    this(cpsjavamoduleJNI.new_StatusCondition2(StatusCondition.getCPtr(condition), condition), true);
  }

  public StatusCondition getStatusCondition() {
    long cPtr = cpsjavamoduleJNI.StatusCondition2_getStatusCondition(swigCPtr, this);
    return (cPtr == 0) ? null : new StatusCondition(cPtr, false);
  }

  public long get_enabled_statuses() {
    return cpsjavamoduleJNI.StatusCondition2_get_enabled_statuses(swigCPtr, this);
  }

  public int set_enabled_statuses(long mask) {
    return cpsjavamoduleJNI.StatusCondition2_set_enabled_statuses(swigCPtr, this, mask);
  }

  public Entity2 get_entity() {
    return new Entity2(cpsjavamoduleJNI.StatusCondition2_get_entity(swigCPtr, this), true);
  }

}
