/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class StatusCondition {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StatusCondition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusCondition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_StatusCondition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setB_trigger_value(boolean value) {
    cpsjavamoduleJNI.StatusCondition_b_trigger_value_set(swigCPtr, this, value);
  }

  public boolean getB_trigger_value() {
    return cpsjavamoduleJNI.StatusCondition_b_trigger_value_get(swigCPtr, this);
  }

  public void setCondition_type(long value) {
    cpsjavamoduleJNI.StatusCondition_condition_type_set(swigCPtr, this, value);
  }

  public long getCondition_type() {
    return cpsjavamoduleJNI.StatusCondition_condition_type_get(swigCPtr, this);
  }

  public StatusCondition() {
    this(cpsjavamoduleJNI.new_StatusCondition(), true);
  }

}
