/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class StringSeq {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StringSeq(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringSeq obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_StringSeq(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI_string(int value) {
    cpsjavamoduleJNI.StringSeq_i_string_set(swigCPtr, this, value);
  }

  public int getI_string() {
    return cpsjavamoduleJNI.StringSeq_i_string_get(swigCPtr, this);
  }

  public void setPp_string(SWIGTYPE_p_p_char value) {
    cpsjavamoduleJNI.StringSeq_pp_string_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getPp_string() {
    long cPtr = cpsjavamoduleJNI.StringSeq_pp_string_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public StringSeq() {
    this(cpsjavamoduleJNI.new_StringSeq(), true);
  }

}
