/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class SubscriberListenerCallBack {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SubscriberListenerCallBack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriberListenerCallBack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_SubscriberListenerCallBack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void on_requested_deadline_missed(DataReader the_reader, RequestedDeadlineMissedStatus status) {
    cpsjavamoduleJNI.SubscriberListenerCallBack_on_requested_deadline_missed(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, RequestedDeadlineMissedStatus.getCPtr(status), status);
  }

  public void on_requested_incompatible_qos(DataReader the_reader, RequestedIncompatibleQosStatus status) {
    cpsjavamoduleJNI.SubscriberListenerCallBack_on_requested_incompatible_qos(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, RequestedIncompatibleQosStatus.getCPtr(status), status);
  }

  public void on_sample_rejected(DataReader the_reader, SampleRejectedStatus status) {
    cpsjavamoduleJNI.SubscriberListenerCallBack_on_sample_rejected(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, SampleRejectedStatus.getCPtr(status), status);
  }

  public void on_liveliness_changed(DataReader the_reader, LivelinessChangedStatus status) {
    cpsjavamoduleJNI.SubscriberListenerCallBack_on_liveliness_changed(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, LivelinessChangedStatus.getCPtr(status), status);
  }

  public void on_data_available(DataReader p_reader) {
    cpsjavamoduleJNI.SubscriberListenerCallBack_on_data_available(swigCPtr, this, DataReader.getCPtr(p_reader), p_reader);
  }

  public void on_subscription_matched(DataReader the_reader, SubscriptionMatchedStatus status) {
    cpsjavamoduleJNI.SubscriberListenerCallBack_on_subscription_matched(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, SubscriptionMatchedStatus.getCPtr(status), status);
  }

  public void on_sample_lost(DataReader the_reader, SampleLostStatus status) {
    cpsjavamoduleJNI.SubscriberListenerCallBack_on_sample_lost(swigCPtr, this, DataReader.getCPtr(the_reader), the_reader, SampleLostStatus.getCPtr(status), status);
  }

  public void on_data_on_readers(Subscriber p_subscriber) {
    cpsjavamoduleJNI.SubscriberListenerCallBack_on_data_on_readers(swigCPtr, this, Subscriber.getCPtr(p_subscriber), p_subscriber);
  }

}
