/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class SubscriberListener2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SubscriberListener2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriberListener2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_SubscriberListener2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SubscriberListener2(SubscriberListener p_listener) {
    this(cpsjavamoduleJNI.new_SubscriberListener2__SWIG_0(SubscriberListener.getCPtr(p_listener), p_listener), true);
  }

  public SubscriberListener2() {
    this(cpsjavamoduleJNI.new_SubscriberListener2__SWIG_1(), true);
  }

  public SubscriberListener getListener() {
    return new SubscriberListener(cpsjavamoduleJNI.SubscriberListener2_getListener(swigCPtr, this), true);
  }

  public SubscriberListener getListenerPtr() {
    long cPtr = cpsjavamoduleJNI.SubscriberListener2_getListenerPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new SubscriberListener(cPtr, false);
  }

  public void setCallback(SubscriberListenerCallBack cb) {
    cpsjavamoduleJNI.SubscriberListener2_setCallback(swigCPtr, this, SubscriberListenerCallBack.getCPtr(cb), cb);
  }

  public static void set_callback(SubscriberListenerCallBack value) {
    cpsjavamoduleJNI.SubscriberListener2__callback_set(SubscriberListenerCallBack.getCPtr(value), value);
  }

  public static SubscriberListenerCallBack get_callback() {
    long cPtr = cpsjavamoduleJNI.SubscriberListener2__callback_get();
    return (cPtr == 0) ? null : new SubscriberListenerCallBack(cPtr, false);
  }

}
