/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class Time_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Time_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Time_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_Time_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSec(int value) {
    cpsjavamoduleJNI.Time_t_sec_set(swigCPtr, this, value);
  }

  public int getSec() {
    return cpsjavamoduleJNI.Time_t_sec_get(swigCPtr, this);
  }

  public void setNanosec(long value) {
    cpsjavamoduleJNI.Time_t_nanosec_set(swigCPtr, this, value);
  }

  public long getNanosec() {
    return cpsjavamoduleJNI.Time_t_nanosec_get(swigCPtr, this);
  }

  public Time_t() {
    this(cpsjavamoduleJNI.new_Time_t(), true);
  }

}
