/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class TopicListener2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TopicListener2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopicListener2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_TopicListener2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TopicListener2(TopicListener p_listener) {
    this(cpsjavamoduleJNI.new_TopicListener2__SWIG_0(TopicListener.getCPtr(p_listener), p_listener), true);
  }

  public TopicListener2() {
    this(cpsjavamoduleJNI.new_TopicListener2__SWIG_1(), true);
  }

  public TopicListener getListener() {
    return new TopicListener(cpsjavamoduleJNI.TopicListener2_getListener(swigCPtr, this), true);
  }

  public TopicListener getListenerPtr() {
    long cPtr = cpsjavamoduleJNI.TopicListener2_getListenerPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new TopicListener(cPtr, false);
  }

  public void setCallback(TopicListenerCallBack cb) {
    cpsjavamoduleJNI.TopicListener2_setCallback(swigCPtr, this, TopicListenerCallBack.getCPtr(cb), cb);
  }

  public static void set_callback(TopicListenerCallBack value) {
    cpsjavamoduleJNI.TopicListener2__callback_set(TopicListenerCallBack.getCPtr(value), value);
  }

  public static TopicListenerCallBack get_callback() {
    long cPtr = cpsjavamoduleJNI.TopicListener2__callback_get();
    return (cPtr == 0) ? null : new TopicListenerCallBack(cPtr, false);
  }

}
