/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class TopicDescription {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TopicDescription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopicDescription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_TopicDescription(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTopic_name(String value) {
    cpsjavamoduleJNI.TopicDescription_topic_name_set(swigCPtr, this, value);
  }

  public String getTopic_name() {
    return cpsjavamoduleJNI.TopicDescription_topic_name_get(swigCPtr, this);
  }

  public void setType_name(String value) {
    cpsjavamoduleJNI.TopicDescription_type_name_set(swigCPtr, this, value);
  }

  public String getType_name() {
    return cpsjavamoduleJNI.TopicDescription_type_name_get(swigCPtr, this);
  }

  public TopicDescription() {
    this(cpsjavamoduleJNI.new_TopicDescription(), true);
  }

}
