/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class TopicQos {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TopicQos(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopicQos obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_TopicQos(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTopic_data(TopicDataQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_topic_data_set(swigCPtr, this, TopicDataQosPolicy.getCPtr(value), value);
  }

  public TopicDataQosPolicy getTopic_data() {
    long cPtr = cpsjavamoduleJNI.TopicQos_topic_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TopicDataQosPolicy(cPtr, false);
  }

  public void setDurability(DurabilityQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_durability_set(swigCPtr, this, DurabilityQosPolicy.getCPtr(value), value);
  }

  public DurabilityQosPolicy getDurability() {
    long cPtr = cpsjavamoduleJNI.TopicQos_durability_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DurabilityQosPolicy(cPtr, false);
  }

  public void setDurability_service(DurabilityServiceQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_durability_service_set(swigCPtr, this, DurabilityServiceQosPolicy.getCPtr(value), value);
  }

  public DurabilityServiceQosPolicy getDurability_service() {
    long cPtr = cpsjavamoduleJNI.TopicQos_durability_service_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DurabilityServiceQosPolicy(cPtr, false);
  }

  public void setDeadline(DeadlineQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_deadline_set(swigCPtr, this, DeadlineQosPolicy.getCPtr(value), value);
  }

  public DeadlineQosPolicy getDeadline() {
    long cPtr = cpsjavamoduleJNI.TopicQos_deadline_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DeadlineQosPolicy(cPtr, false);
  }

  public void setLatency_budget(LatencyBudgetQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_latency_budget_set(swigCPtr, this, LatencyBudgetQosPolicy.getCPtr(value), value);
  }

  public LatencyBudgetQosPolicy getLatency_budget() {
    long cPtr = cpsjavamoduleJNI.TopicQos_latency_budget_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LatencyBudgetQosPolicy(cPtr, false);
  }

  public void setLiveliness(LivelinessQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_liveliness_set(swigCPtr, this, LivelinessQosPolicy.getCPtr(value), value);
  }

  public LivelinessQosPolicy getLiveliness() {
    long cPtr = cpsjavamoduleJNI.TopicQos_liveliness_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LivelinessQosPolicy(cPtr, false);
  }

  public void setReliability(ReliabilityQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_reliability_set(swigCPtr, this, ReliabilityQosPolicy.getCPtr(value), value);
  }

  public ReliabilityQosPolicy getReliability() {
    long cPtr = cpsjavamoduleJNI.TopicQos_reliability_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ReliabilityQosPolicy(cPtr, false);
  }

  public void setDestination_order(DestinationOrderQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_destination_order_set(swigCPtr, this, DestinationOrderQosPolicy.getCPtr(value), value);
  }

  public DestinationOrderQosPolicy getDestination_order() {
    long cPtr = cpsjavamoduleJNI.TopicQos_destination_order_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DestinationOrderQosPolicy(cPtr, false);
  }

  public void setHistory(HistoryQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_history_set(swigCPtr, this, HistoryQosPolicy.getCPtr(value), value);
  }

  public HistoryQosPolicy getHistory() {
    long cPtr = cpsjavamoduleJNI.TopicQos_history_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HistoryQosPolicy(cPtr, false);
  }

  public void setResource_limits(ResourceLimitsQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_resource_limits_set(swigCPtr, this, ResourceLimitsQosPolicy.getCPtr(value), value);
  }

  public ResourceLimitsQosPolicy getResource_limits() {
    long cPtr = cpsjavamoduleJNI.TopicQos_resource_limits_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ResourceLimitsQosPolicy(cPtr, false);
  }

  public void setTransport_priority(TransportPriorityQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_transport_priority_set(swigCPtr, this, TransportPriorityQosPolicy.getCPtr(value), value);
  }

  public TransportPriorityQosPolicy getTransport_priority() {
    long cPtr = cpsjavamoduleJNI.TopicQos_transport_priority_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TransportPriorityQosPolicy(cPtr, false);
  }

  public void setLifespan(LifespanQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_lifespan_set(swigCPtr, this, LifespanQosPolicy.getCPtr(value), value);
  }

  public LifespanQosPolicy getLifespan() {
    long cPtr = cpsjavamoduleJNI.TopicQos_lifespan_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LifespanQosPolicy(cPtr, false);
  }

  public void setOwnership(OwnershipQosPolicy value) {
    cpsjavamoduleJNI.TopicQos_ownership_set(swigCPtr, this, OwnershipQosPolicy.getCPtr(value), value);
  }

  public OwnershipQosPolicy getOwnership() {
    long cPtr = cpsjavamoduleJNI.TopicQos_ownership_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OwnershipQosPolicy(cPtr, false);
  }

  public TopicQos() {
    this(cpsjavamoduleJNI.new_TopicQos(), true);
  }

}
