/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class TopicListenerCallBack {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TopicListenerCallBack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopicListenerCallBack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_TopicListenerCallBack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    cpsjavamoduleJNI.TopicListenerCallBack_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    cpsjavamoduleJNI.TopicListenerCallBack_change_ownership(this, swigCPtr, true);
  }

  public void on_inconsistent_topic(Topic the_topic, InconsistentTopicStatus status) {
    cpsjavamoduleJNI.TopicListenerCallBack_on_inconsistent_topic(swigCPtr, this, Topic.getCPtr(the_topic), the_topic, InconsistentTopicStatus.getCPtr(status), status);
  }

  public TopicListenerCallBack() {
    this(cpsjavamoduleJNI.new_TopicListenerCallBack(), true);
    cpsjavamoduleJNI.TopicListenerCallBack_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
