/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class TopicDescription2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TopicDescription2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopicDescription2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_TopicDescription2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TopicDescription2(TopicDescription topicDescription) {
    this(cpsjavamoduleJNI.new_TopicDescription2(TopicDescription.getCPtr(topicDescription), topicDescription), true);
  }

  public TopicDescription getTopicDescription() {
    long cPtr = cpsjavamoduleJNI.TopicDescription2_getTopicDescription(swigCPtr, this);
    return (cPtr == 0) ? null : new TopicDescription(cPtr, false);
  }

  public String get_type_name() {
    return cpsjavamoduleJNI.TopicDescription2_get_type_name(swigCPtr, this);
  }

  public String get_name() {
    return cpsjavamoduleJNI.TopicDescription2_get_name(swigCPtr, this);
  }

  public DomainParticipant2 get_participant() {
    return new DomainParticipant2(cpsjavamoduleJNI.TopicDescription2_get_participant(swigCPtr, this), true);
  }

}
