/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class Topic2 extends Entity2 {
  private long swigCPtr;

  protected Topic2(long cPtr, boolean cMemoryOwn) {
    super(cpsjavamoduleJNI.Topic2_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Topic2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_Topic2(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Topic2(Topic topic) {
    this(cpsjavamoduleJNI.new_Topic2(Topic.getCPtr(topic), topic), true);
  }

  public Topic getTopic() {
    long cPtr = cpsjavamoduleJNI.Topic2_getTopic(swigCPtr, this);
    return (cPtr == 0) ? null : new Topic(cPtr, false);
  }

  public int set_qos(TopicQos qos) {
    return cpsjavamoduleJNI.Topic2_set_qos(swigCPtr, this, TopicQos.getCPtr(qos), qos);
  }

  public int get_qos(TopicQos qos) {
    return cpsjavamoduleJNI.Topic2_get_qos(swigCPtr, this, TopicQos.getCPtr(qos), qos);
  }

  public int set_listener(TopicListener2 listener, long mask) {
    return cpsjavamoduleJNI.Topic2_set_listener(swigCPtr, this, TopicListener2.getCPtr(listener), listener, mask);
  }

  public TopicListener2 get_listener() {
    return new TopicListener2(cpsjavamoduleJNI.Topic2_get_listener(swigCPtr, this), true);
  }

  public int get_inconsistent_topic_status(InconsistentTopicStatus a_status) {
    return cpsjavamoduleJNI.Topic2_get_inconsistent_topic_status(swigCPtr, this, InconsistentTopicStatus.getCPtr(a_status), a_status);
  }

}
