/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kr.re.etri.cps.jni;

public class WriterDataLifecycleQosPolicy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected WriterDataLifecycleQosPolicy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WriterDataLifecycleQosPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cpsjavamoduleJNI.delete_WriterDataLifecycleQosPolicy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAutodispose_unregistered_instances(boolean value) {
    cpsjavamoduleJNI.WriterDataLifecycleQosPolicy_autodispose_unregistered_instances_set(swigCPtr, this, value);
  }

  public boolean getAutodispose_unregistered_instances() {
    return cpsjavamoduleJNI.WriterDataLifecycleQosPolicy_autodispose_unregistered_instances_get(swigCPtr, this);
  }

  public WriterDataLifecycleQosPolicy() {
    this(cpsjavamoduleJNI.new_WriterDataLifecycleQosPolicy(), true);
  }

}
