/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ConditionSeq : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConditionSeq(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ConditionSeq obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ConditionSeq() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_ConditionSeq(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int i_seq {
    set {
      cpscsharpmodulePINVOKE.ConditionSeq_i_seq_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.ConditionSeq_i_seq_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_Condition pp_conditions {
    set {
      cpscsharpmodulePINVOKE.ConditionSeq_pp_conditions_set(swigCPtr, SWIGTYPE_p_p_Condition.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.ConditionSeq_pp_conditions_get(swigCPtr);
      SWIGTYPE_p_p_Condition ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_Condition(cPtr, false);
      return ret;
    } 
  }

  public ConditionSeq() : this(cpscsharpmodulePINVOKE.new_ConditionSeq(), true) {
  }

}
