/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Condition2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Condition2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Condition2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Condition2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_Condition2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Condition2(Condition condition) : this(cpscsharpmodulePINVOKE.new_Condition2(Condition.getCPtr(condition)), true) {
  }

  public Condition getCondition() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.Condition2_getCondition(swigCPtr);
    Condition ret = (cPtr == IntPtr.Zero) ? null : new Condition(cPtr, false);
    return ret;
  }

  public bool get_trigger_value() {
    bool ret = cpscsharpmodulePINVOKE.Condition2_get_trigger_value(swigCPtr);
    return ret;
  }

}
