/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ContentFilteredTopic2 : Entity2 {
  private HandleRef swigCPtr;

  internal ContentFilteredTopic2(IntPtr cPtr, bool cMemoryOwn) : base(cpscsharpmodulePINVOKE.ContentFilteredTopic2_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ContentFilteredTopic2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ContentFilteredTopic2() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_ContentFilteredTopic2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ContentFilteredTopic2(ContentFilteredTopic topic) : this(cpscsharpmodulePINVOKE.new_ContentFilteredTopic2(ContentFilteredTopic.getCPtr(topic)), true) {
  }

  public ContentFilteredTopic getContentFilteredTopic() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.ContentFilteredTopic2_getContentFilteredTopic(swigCPtr);
    ContentFilteredTopic ret = (cPtr == IntPtr.Zero) ? null : new ContentFilteredTopic(cPtr, false);
    return ret;
  }

  public string get_filter_expression() {
    string ret = cpscsharpmodulePINVOKE.ContentFilteredTopic2_get_filter_expression(swigCPtr);
    return ret;
  }

  public int get_expression_parameters(StringSeq expression_parameters) {
    int ret = cpscsharpmodulePINVOKE.ContentFilteredTopic2_get_expression_parameters(swigCPtr, StringSeq.getCPtr(expression_parameters));
    if (cpscsharpmodulePINVOKE.SWIGPendingException.Pending) throw cpscsharpmodulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int set_expression_parameters(StringSeq expression_parameters) {
    int ret = cpscsharpmodulePINVOKE.ContentFilteredTopic2_set_expression_parameters(swigCPtr, StringSeq.getCPtr(expression_parameters));
    if (cpscsharpmodulePINVOKE.SWIGPendingException.Pending) throw cpscsharpmodulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Topic2 get_related_topic() {
    Topic2 ret = new Topic2(cpscsharpmodulePINVOKE.ContentFilteredTopic2_get_related_topic(swigCPtr), true);
    return ret;
  }

}
