/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class cpscsharpmodule {
  public static int INVALID_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.INVALID_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int USERDATA_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.USERDATA_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int DURABILITY_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.DURABILITY_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int PRESENTATION_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.PRESENTATION_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int DEADLINE_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.DEADLINE_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int LATENCYBUDGET_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.LATENCYBUDGET_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int OWNERSHIP_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.OWNERSHIP_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int OWNERSHIPSTRENGTH_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.OWNERSHIPSTRENGTH_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int LIVELINESS_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.LIVELINESS_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int TIMEBASEDFILTER_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.TIMEBASEDFILTER_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int PARTITION_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.PARTITION_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int RELIABILITY_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.RELIABILITY_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int DESTINATIONORDER_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.DESTINATIONORDER_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int HISTORY_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.HISTORY_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int RESOURCELIMITS_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.RESOURCELIMITS_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int ENTITYFACTORY_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.ENTITYFACTORY_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int WRITERDATALIFECYCLE_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.WRITERDATALIFECYCLE_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int READERDATALIFECYCLE_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.READERDATALIFECYCLE_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int TOPICDATA_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.TOPICDATA_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int GROUPDATA_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.GROUPDATA_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int TRANSPORTPRIORITY_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.TRANSPORTPRIORITY_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int LIFESPAN_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.LIFESPAN_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static int DURABILITYSERVICE_QOS_POLICY_ID {
    get {
      int ret = cpscsharpmodulePINVOKE.DURABILITYSERVICE_QOS_POLICY_ID_get();
      return ret;
    } 
  }

  public static uint INCONSISTENT_TOPIC_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.INCONSISTENT_TOPIC_STATUS_get();
      return ret;
    } 
  }

  public static uint OFFERED_DEADLINE_MISSED_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.OFFERED_DEADLINE_MISSED_STATUS_get();
      return ret;
    } 
  }

  public static uint REQUESTED_DEADLINE_MISSED_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.REQUESTED_DEADLINE_MISSED_STATUS_get();
      return ret;
    } 
  }

  public static uint OFFERED_INCOMPATIBLE_QOS_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.OFFERED_INCOMPATIBLE_QOS_STATUS_get();
      return ret;
    } 
  }

  public static uint REQUESTED_INCOMPATIBLE_QOS_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.REQUESTED_INCOMPATIBLE_QOS_STATUS_get();
      return ret;
    } 
  }

  public static uint SAMPLE_LOST_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.SAMPLE_LOST_STATUS_get();
      return ret;
    } 
  }

  public static uint SAMPLE_REJECTED_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.SAMPLE_REJECTED_STATUS_get();
      return ret;
    } 
  }

  public static uint DATA_ON_READERS_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.DATA_ON_READERS_STATUS_get();
      return ret;
    } 
  }

  public static uint DATA_AVAILABLE_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.DATA_AVAILABLE_STATUS_get();
      return ret;
    } 
  }

  public static uint LIVELINESS_LOST_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.LIVELINESS_LOST_STATUS_get();
      return ret;
    } 
  }

  public static uint LIVELINESS_CHANGED_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.LIVELINESS_CHANGED_STATUS_get();
      return ret;
    } 
  }

  public static uint PUBLICATION_MATCHED_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.PUBLICATION_MATCHED_STATUS_get();
      return ret;
    } 
  }

  public static uint SUBSCRIPTION_MATCHED_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.SUBSCRIPTION_MATCHED_STATUS_get();
      return ret;
    } 
  }

  public static uint ALL_ENABLE_STATUS {
    get {
      uint ret = cpscsharpmodulePINVOKE.ALL_ENABLE_STATUS_get();
      return ret;
    } 
  }

  public static readonly int SWIG_ON = cpscsharpmodulePINVOKE.SWIG_ON_get();
  public static readonly int RETURN_CODE_T_DEFINE = cpscsharpmodulePINVOKE.RETURN_CODE_T_DEFINE_get();
  public static readonly int HANDLE_TYPE_NATIVE_DEFINE = cpscsharpmodulePINVOKE.HANDLE_TYPE_NATIVE_DEFINE_get();
}
