/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DataReaderSeq : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DataReaderSeq(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DataReaderSeq obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DataReaderSeq() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_DataReaderSeq(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int i_seq {
    set {
      cpscsharpmodulePINVOKE.DataReaderSeq_i_seq_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.DataReaderSeq_i_seq_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_DataReader pp_datareaders {
    set {
      cpscsharpmodulePINVOKE.DataReaderSeq_pp_datareaders_set(swigCPtr, SWIGTYPE_p_p_DataReader.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.DataReaderSeq_pp_datareaders_get(swigCPtr);
      SWIGTYPE_p_p_DataReader ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_DataReader(cPtr, false);
      return ret;
    } 
  }

  public DataReaderSeq() : this(cpscsharpmodulePINVOKE.new_DataReaderSeq(), true) {
  }

}
