/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DestinationOrderQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DestinationOrderQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DestinationOrderQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DestinationOrderQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_DestinationOrderQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DestinationOrderQosPolicyKind kind {
    set {
      cpscsharpmodulePINVOKE.DestinationOrderQosPolicy_kind_set(swigCPtr, (int)value);
    } 
    get {
      DestinationOrderQosPolicyKind ret = (DestinationOrderQosPolicyKind)cpscsharpmodulePINVOKE.DestinationOrderQosPolicy_kind_get(swigCPtr);
      return ret;
    } 
  }

  public DestinationOrderQosPolicy() : this(cpscsharpmodulePINVOKE.new_DestinationOrderQosPolicy(), true) {
  }

}
