/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DomainParticipantQos2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DomainParticipantQos2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DomainParticipantQos2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DomainParticipantQos2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_DomainParticipantQos2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DomainParticipantQos2() : this(cpscsharpmodulePINVOKE.new_DomainParticipantQos2(), true) {
  }

  public DomainParticipantQos getQos() {
    DomainParticipantQos ret = new DomainParticipantQos(cpscsharpmodulePINVOKE.DomainParticipantQos2_getQos(swigCPtr), true);
    return ret;
  }

}
