/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DurabilityQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DurabilityQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DurabilityQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DurabilityQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_DurabilityQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DurabilityQosPolicyKind kind {
    set {
      cpscsharpmodulePINVOKE.DurabilityQosPolicy_kind_set(swigCPtr, (int)value);
    } 
    get {
      DurabilityQosPolicyKind ret = (DurabilityQosPolicyKind)cpscsharpmodulePINVOKE.DurabilityQosPolicy_kind_get(swigCPtr);
      return ret;
    } 
  }

  public DurabilityQosPolicy() : this(cpscsharpmodulePINVOKE.new_DurabilityQosPolicy(), true) {
  }

}
