/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DurabilityServiceQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DurabilityServiceQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DurabilityServiceQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DurabilityServiceQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_DurabilityServiceQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Duration_t service_cleanup_delay {
    set {
      cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_service_cleanup_delay_set(swigCPtr, Duration_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_service_cleanup_delay_get(swigCPtr);
      Duration_t ret = (cPtr == IntPtr.Zero) ? null : new Duration_t(cPtr, false);
      return ret;
    } 
  }

  public HistoryQosPolicyKind history_kind {
    set {
      cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_history_kind_set(swigCPtr, (int)value);
    } 
    get {
      HistoryQosPolicyKind ret = (HistoryQosPolicyKind)cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_history_kind_get(swigCPtr);
      return ret;
    } 
  }

  public int history_depth {
    set {
      cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_history_depth_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_history_depth_get(swigCPtr);
      return ret;
    } 
  }

  public int max_samples {
    set {
      cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_max_samples_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_max_samples_get(swigCPtr);
      return ret;
    } 
  }

  public int max_instances {
    set {
      cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_max_instances_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_max_instances_get(swigCPtr);
      return ret;
    } 
  }

  public int max_samples_per_instance {
    set {
      cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_max_samples_per_instance_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.DurabilityServiceQosPolicy_max_samples_per_instance_get(swigCPtr);
      return ret;
    } 
  }

  public DurabilityServiceQosPolicy() : this(cpscsharpmodulePINVOKE.new_DurabilityServiceQosPolicy(), true) {
  }

}
