/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Duration_t : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Duration_t(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Duration_t obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Duration_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_Duration_t(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int sec {
    set {
      cpscsharpmodulePINVOKE.Duration_t_sec_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.Duration_t_sec_get(swigCPtr);
      return ret;
    } 
  }

  public uint nanosec {
    set {
      cpscsharpmodulePINVOKE.Duration_t_nanosec_set(swigCPtr, value);
    } 
    get {
      uint ret = cpscsharpmodulePINVOKE.Duration_t_nanosec_get(swigCPtr);
      return ret;
    } 
  }

  public Duration_t() : this(cpscsharpmodulePINVOKE.new_Duration_t(), true) {
  }

}
