/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class EntityFactoryQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EntityFactoryQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(EntityFactoryQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~EntityFactoryQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_EntityFactoryQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public bool autoenable_created_entities {
    set {
      cpscsharpmodulePINVOKE.EntityFactoryQosPolicy_autoenable_created_entities_set(swigCPtr, value);
    } 
    get {
      bool ret = cpscsharpmodulePINVOKE.EntityFactoryQosPolicy_autoenable_created_entities_get(swigCPtr);
      return ret;
    } 
  }

  public EntityFactoryQosPolicy() : this(cpscsharpmodulePINVOKE.new_EntityFactoryQosPolicy(), true) {
  }

}
