/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Entity2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Entity2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Entity2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Entity2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_Entity2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Entity2(Entity entity) : this(cpscsharpmodulePINVOKE.new_Entity2(Entity.getCPtr(entity)), true) {
  }

  public Entity getEntity() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.Entity2_getEntity(swigCPtr);
    Entity ret = (cPtr == IntPtr.Zero) ? null : new Entity(cPtr, false);
    return ret;
  }

  public int enable() {
    int ret = cpscsharpmodulePINVOKE.Entity2_enable(swigCPtr);
    return ret;
  }

  public StatusCondition2 get_statuscondition() {
    StatusCondition2 ret = new StatusCondition2(cpscsharpmodulePINVOKE.Entity2_get_statuscondition(swigCPtr), true);
    return ret;
  }

  public uint get_status_changes() {
    uint ret = cpscsharpmodulePINVOKE.Entity2_get_status_changes(swigCPtr);
    return ret;
  }

  public int get_instance_handle() {
    int ret = cpscsharpmodulePINVOKE.Entity2_get_instance_handle(swigCPtr);
    return ret;
  }

}
