/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FooDataReader : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FooDataReader(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FooDataReader obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FooDataReader() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_FooDataReader(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int i_entity_type {
    set {
      cpscsharpmodulePINVOKE.FooDataReader_i_entity_type_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.FooDataReader_i_entity_type_get(swigCPtr);
      return ret;
    } 
  }

  public FooDataReader() : this(cpscsharpmodulePINVOKE.new_FooDataReader(), true) {
  }

}
