/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum FooRet {
  OK,
  PARAMETER_NOT_EXIST,
  TYPE_WRONG,
  FOO_NOT_EXIST,
  FooTypeSupport2_NOT_EXIST
}
