/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FooSeq : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FooSeq(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FooSeq obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FooSeq() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_FooSeq(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int i_seq {
    set {
      cpscsharpmodulePINVOKE.FooSeq_i_seq_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.FooSeq_i_seq_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_Foo pp_foo {
    set {
      cpscsharpmodulePINVOKE.FooSeq_pp_foo_set(swigCPtr, SWIGTYPE_p_p_Foo.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.FooSeq_pp_foo_get(swigCPtr);
      SWIGTYPE_p_p_Foo ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_Foo(cPtr, false);
      return ret;
    } 
  }

  public FooSeq() : this(cpscsharpmodulePINVOKE.new_FooSeq(), true) {
  }

}
