/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FooTypeSupport2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FooTypeSupport2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FooTypeSupport2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FooTypeSupport2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_FooTypeSupport2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public FooTypeSupport2() : this(cpscsharpmodulePINVOKE.new_FooTypeSupport2(), true) {
  }

  public FooTypeSupport getFooTypeSupport() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.FooTypeSupport2_getFooTypeSupport(swigCPtr);
    FooTypeSupport ret = (cPtr == IntPtr.Zero) ? null : new FooTypeSupport(cPtr, false);
    return ret;
  }

  public int register_type(DomainParticipant2 participant, string type_name) {
    int ret = cpscsharpmodulePINVOKE.FooTypeSupport2_register_type(swigCPtr, DomainParticipant2.getCPtr(participant), type_name);
    if (cpscsharpmodulePINVOKE.SWIGPendingException.Pending) throw cpscsharpmodulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string get_type_name() {
    string ret = cpscsharpmodulePINVOKE.FooTypeSupport2_get_type_name(swigCPtr);
    return ret;
  }

  public bool insert_parameter(string parameter_name, SUPPORT_TYPE type, bool is_key) {
    bool ret = cpscsharpmodulePINVOKE.FooTypeSupport2_insert_parameter__SWIG_0(swigCPtr, parameter_name, (int)type, is_key);
    return ret;
  }

  public bool insert_parameter(string parameter_name, SUPPORT_TYPE type) {
    bool ret = cpscsharpmodulePINVOKE.FooTypeSupport2_insert_parameter__SWIG_1(swigCPtr, parameter_name, (int)type);
    return ret;
  }

  public bool insert_parameter_struct(string parameter_name, int size, bool is_key) {
    bool ret = cpscsharpmodulePINVOKE.FooTypeSupport2_insert_parameter_struct__SWIG_0(swigCPtr, parameter_name, size, is_key);
    return ret;
  }

  public bool insert_parameter_struct(string parameter_name, int size) {
    bool ret = cpscsharpmodulePINVOKE.FooTypeSupport2_insert_parameter_struct__SWIG_1(swigCPtr, parameter_name, size);
    return ret;
  }

  public void setFootypeSize(int size) {
    cpscsharpmodulePINVOKE.FooTypeSupport2_setFootypeSize(swigCPtr, size);
  }

}
