/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FooTypeSupport : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FooTypeSupport(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FooTypeSupport obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FooTypeSupport() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_FooTypeSupport(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int i_size {
    set {
      cpscsharpmodulePINVOKE.FooTypeSupport_i_size_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.FooTypeSupport_i_size_get(swigCPtr);
      return ret;
    } 
  }

  public int i_parameters {
    set {
      cpscsharpmodulePINVOKE.FooTypeSupport_i_parameters_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.FooTypeSupport_i_parameters_get(swigCPtr);
      return ret;
    } 
  }

  public FooTypeSupport() : this(cpscsharpmodulePINVOKE.new_FooTypeSupport(), true) {
  }

}
