/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class HistoryQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HistoryQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(HistoryQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~HistoryQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_HistoryQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public HistoryQosPolicyKind kind {
    set {
      cpscsharpmodulePINVOKE.HistoryQosPolicy_kind_set(swigCPtr, (int)value);
    } 
    get {
      HistoryQosPolicyKind ret = (HistoryQosPolicyKind)cpscsharpmodulePINVOKE.HistoryQosPolicy_kind_get(swigCPtr);
      return ret;
    } 
  }

  public int depth {
    set {
      cpscsharpmodulePINVOKE.HistoryQosPolicy_depth_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.HistoryQosPolicy_depth_get(swigCPtr);
      return ret;
    } 
  }

  public HistoryQosPolicy() : this(cpscsharpmodulePINVOKE.new_HistoryQosPolicy(), true) {
  }

}
