/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class InstanceHandleSeq : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal InstanceHandleSeq(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(InstanceHandleSeq obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~InstanceHandleSeq() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_InstanceHandleSeq(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int i_seq {
    set {
      cpscsharpmodulePINVOKE.InstanceHandleSeq_i_seq_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.InstanceHandleSeq_i_seq_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_long pp_instancehandle {
    set {
      cpscsharpmodulePINVOKE.InstanceHandleSeq_pp_instancehandle_set(swigCPtr, SWIGTYPE_p_p_long.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.InstanceHandleSeq_pp_instancehandle_get(swigCPtr);
      SWIGTYPE_p_p_long ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_long(cPtr, false);
      return ret;
    } 
  }

  public InstanceHandleSeq() : this(cpscsharpmodulePINVOKE.new_InstanceHandleSeq(), true) {
  }

}
