/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class LivelinessChangedStatus : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LivelinessChangedStatus(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(LivelinessChangedStatus obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~LivelinessChangedStatus() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_LivelinessChangedStatus(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int alive_count {
    set {
      cpscsharpmodulePINVOKE.LivelinessChangedStatus_alive_count_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.LivelinessChangedStatus_alive_count_get(swigCPtr);
      return ret;
    } 
  }

  public int not_alive_count {
    set {
      cpscsharpmodulePINVOKE.LivelinessChangedStatus_not_alive_count_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.LivelinessChangedStatus_not_alive_count_get(swigCPtr);
      return ret;
    } 
  }

  public int alive_count_change {
    set {
      cpscsharpmodulePINVOKE.LivelinessChangedStatus_alive_count_change_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.LivelinessChangedStatus_alive_count_change_get(swigCPtr);
      return ret;
    } 
  }

  public int not_alive_count_change {
    set {
      cpscsharpmodulePINVOKE.LivelinessChangedStatus_not_alive_count_change_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.LivelinessChangedStatus_not_alive_count_change_get(swigCPtr);
      return ret;
    } 
  }

  public int last_publication_handle {
    set {
      cpscsharpmodulePINVOKE.LivelinessChangedStatus_last_publication_handle_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.LivelinessChangedStatus_last_publication_handle_get(swigCPtr);
      return ret;
    } 
  }

  public LivelinessChangedStatus() : this(cpscsharpmodulePINVOKE.new_LivelinessChangedStatus(), true) {
  }

}
