/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class LivelinessQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LivelinessQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(LivelinessQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~LivelinessQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_LivelinessQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public LivelinessQosPolicyKind kind {
    set {
      cpscsharpmodulePINVOKE.LivelinessQosPolicy_kind_set(swigCPtr, (int)value);
    } 
    get {
      LivelinessQosPolicyKind ret = (LivelinessQosPolicyKind)cpscsharpmodulePINVOKE.LivelinessQosPolicy_kind_get(swigCPtr);
      return ret;
    } 
  }

  public Duration_t lease_duration {
    set {
      cpscsharpmodulePINVOKE.LivelinessQosPolicy_lease_duration_set(swigCPtr, Duration_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.LivelinessQosPolicy_lease_duration_get(swigCPtr);
      Duration_t ret = (cPtr == IntPtr.Zero) ? null : new Duration_t(cPtr, false);
      return ret;
    } 
  }

  public LivelinessQosPolicy() : this(cpscsharpmodulePINVOKE.new_LivelinessQosPolicy(), true) {
  }

}
