/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class message_t : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal message_t(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(message_t obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~message_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_message_t(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int i_datasize {
    set {
      cpscsharpmodulePINVOKE.message_t_i_datasize_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.message_t_i_datasize_get(swigCPtr);
      return ret;
    } 
  }

  public IntPtr v_data {
    set {
      cpscsharpmodulePINVOKE.message_t_v_data_set(swigCPtr, new HandleRef(null, value));
    } get{IntPtr res = cpscsharpmodulePINVOKE.message_t_v_data_get(swigCPtr); ; return res;}
  }

  public message_t() : this(cpscsharpmodulePINVOKE.new_message_t(), true) {
  }

}
