/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Message2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Message2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Message2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Message2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_Message2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Message2() : this(cpscsharpmodulePINVOKE.new_Message2__SWIG_0(), true) {
  }

  public Message2(message_t message) : this(cpscsharpmodulePINVOKE.new_Message2__SWIG_1(message_t.getCPtr(message)), true) {
  }

  public void removeMessage() {
    cpscsharpmodulePINVOKE.Message2_removeMessage(swigCPtr);
  }

  public IntPtr getValue() {IntPtr res = cpscsharpmodulePINVOKE.Message2_getValue(swigCPtr); ; return res;}

}
