/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class MultiTopic2 : Entity2 {
  private HandleRef swigCPtr;

  internal MultiTopic2(IntPtr cPtr, bool cMemoryOwn) : base(cpscsharpmodulePINVOKE.MultiTopic2_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MultiTopic2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MultiTopic2() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_MultiTopic2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public MultiTopic2(MultiTopic topic) : this(cpscsharpmodulePINVOKE.new_MultiTopic2(MultiTopic.getCPtr(topic)), true) {
  }

  public MultiTopic getMultiTopic() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.MultiTopic2_getMultiTopic(swigCPtr);
    MultiTopic ret = (cPtr == IntPtr.Zero) ? null : new MultiTopic(cPtr, false);
    return ret;
  }

  public string get_subscription_expression() {
    string ret = cpscsharpmodulePINVOKE.MultiTopic2_get_subscription_expression(swigCPtr);
    return ret;
  }

  public int get_expression_parameters(StringSeq expression_parameters) {
    int ret = cpscsharpmodulePINVOKE.MultiTopic2_get_expression_parameters(swigCPtr, StringSeq.getCPtr(expression_parameters));
    if (cpscsharpmodulePINVOKE.SWIGPendingException.Pending) throw cpscsharpmodulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int set_expression_parameters(StringSeq expression_parameters) {
    int ret = cpscsharpmodulePINVOKE.MultiTopic2_set_expression_parameters(swigCPtr, StringSeq.getCPtr(expression_parameters));
    if (cpscsharpmodulePINVOKE.SWIGPendingException.Pending) throw cpscsharpmodulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
