/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class OfferedIncompatibleQosStatus : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OfferedIncompatibleQosStatus(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OfferedIncompatibleQosStatus obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OfferedIncompatibleQosStatus() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_OfferedIncompatibleQosStatus(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int total_count {
    set {
      cpscsharpmodulePINVOKE.OfferedIncompatibleQosStatus_total_count_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.OfferedIncompatibleQosStatus_total_count_get(swigCPtr);
      return ret;
    } 
  }

  public int total_count_change {
    set {
      cpscsharpmodulePINVOKE.OfferedIncompatibleQosStatus_total_count_change_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.OfferedIncompatibleQosStatus_total_count_change_get(swigCPtr);
      return ret;
    } 
  }

  public int last_policy_id {
    set {
      cpscsharpmodulePINVOKE.OfferedIncompatibleQosStatus_last_policy_id_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.OfferedIncompatibleQosStatus_last_policy_id_get(swigCPtr);
      return ret;
    } 
  }

  public QosPolicyCount policies {
    set {
      cpscsharpmodulePINVOKE.OfferedIncompatibleQosStatus_policies_set(swigCPtr, QosPolicyCount.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.OfferedIncompatibleQosStatus_policies_get(swigCPtr);
      QosPolicyCount ret = (cPtr == IntPtr.Zero) ? null : new QosPolicyCount(cPtr, false);
      return ret;
    } 
  }

  public OfferedIncompatibleQosStatus() : this(cpscsharpmodulePINVOKE.new_OfferedIncompatibleQosStatus(), true) {
  }

}
