/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class OfferedDeadlineMissedStatus : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OfferedDeadlineMissedStatus(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OfferedDeadlineMissedStatus obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OfferedDeadlineMissedStatus() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_OfferedDeadlineMissedStatus(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int total_count {
    set {
      cpscsharpmodulePINVOKE.OfferedDeadlineMissedStatus_total_count_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.OfferedDeadlineMissedStatus_total_count_get(swigCPtr);
      return ret;
    } 
  }

  public int total_count_change {
    set {
      cpscsharpmodulePINVOKE.OfferedDeadlineMissedStatus_total_count_change_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.OfferedDeadlineMissedStatus_total_count_change_get(swigCPtr);
      return ret;
    } 
  }

  public int last_instance_handle {
    set {
      cpscsharpmodulePINVOKE.OfferedDeadlineMissedStatus_last_instance_handle_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.OfferedDeadlineMissedStatus_last_instance_handle_get(swigCPtr);
      return ret;
    } 
  }

  public OfferedDeadlineMissedStatus() : this(cpscsharpmodulePINVOKE.new_OfferedDeadlineMissedStatus(), true) {
  }

}
