/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PresentationQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PresentationQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PresentationQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PresentationQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_PresentationQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PresentationQosPolicyAccessScopeKind access_scope {
    set {
      cpscsharpmodulePINVOKE.PresentationQosPolicy_access_scope_set(swigCPtr, (int)value);
    } 
    get {
      PresentationQosPolicyAccessScopeKind ret = (PresentationQosPolicyAccessScopeKind)cpscsharpmodulePINVOKE.PresentationQosPolicy_access_scope_get(swigCPtr);
      return ret;
    } 
  }

  public bool coherent_access {
    set {
      cpscsharpmodulePINVOKE.PresentationQosPolicy_coherent_access_set(swigCPtr, value);
    } 
    get {
      bool ret = cpscsharpmodulePINVOKE.PresentationQosPolicy_coherent_access_get(swigCPtr);
      return ret;
    } 
  }

  public bool ordered_access {
    set {
      cpscsharpmodulePINVOKE.PresentationQosPolicy_ordered_access_set(swigCPtr, value);
    } 
    get {
      bool ret = cpscsharpmodulePINVOKE.PresentationQosPolicy_ordered_access_get(swigCPtr);
      return ret;
    } 
  }

  public PresentationQosPolicy() : this(cpscsharpmodulePINVOKE.new_PresentationQosPolicy(), true) {
  }

}
