/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PublisherListener2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PublisherListener2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PublisherListener2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PublisherListener2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_PublisherListener2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PublisherListener2(PublisherListener p_listener) : this(cpscsharpmodulePINVOKE.new_PublisherListener2__SWIG_0(PublisherListener.getCPtr(p_listener)), true) {
  }

  public PublisherListener2() : this(cpscsharpmodulePINVOKE.new_PublisherListener2__SWIG_1(), true) {
  }

  public PublisherListener getListener() {
    PublisherListener ret = new PublisherListener(cpscsharpmodulePINVOKE.PublisherListener2_getListener(swigCPtr), true);
    return ret;
  }

  public PublisherListener getListenerPtr() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.PublisherListener2_getListenerPtr(swigCPtr);
    PublisherListener ret = (cPtr == IntPtr.Zero) ? null : new PublisherListener(cPtr, false);
    return ret;
  }

  public void setCallback(PublisherListenerCallBack cb) {
    cpscsharpmodulePINVOKE.PublisherListener2_setCallback(swigCPtr, PublisherListenerCallBack.getCPtr(cb));
  }

  public static PublisherListenerCallBack _callback {
    set {
      cpscsharpmodulePINVOKE.PublisherListener2__callback_set(PublisherListenerCallBack.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.PublisherListener2__callback_get();
      PublisherListenerCallBack ret = (cPtr == IntPtr.Zero) ? null : new PublisherListenerCallBack(cPtr, false);
      return ret;
    } 
  }

}
