/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PublicationMatchedStatus : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PublicationMatchedStatus(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PublicationMatchedStatus obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PublicationMatchedStatus() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_PublicationMatchedStatus(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int total_count {
    set {
      cpscsharpmodulePINVOKE.PublicationMatchedStatus_total_count_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.PublicationMatchedStatus_total_count_get(swigCPtr);
      return ret;
    } 
  }

  public int total_count_change {
    set {
      cpscsharpmodulePINVOKE.PublicationMatchedStatus_total_count_change_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.PublicationMatchedStatus_total_count_change_get(swigCPtr);
      return ret;
    } 
  }

  public int current_count {
    set {
      cpscsharpmodulePINVOKE.PublicationMatchedStatus_current_count_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.PublicationMatchedStatus_current_count_get(swigCPtr);
      return ret;
    } 
  }

  public int current_count_change {
    set {
      cpscsharpmodulePINVOKE.PublicationMatchedStatus_current_count_change_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.PublicationMatchedStatus_current_count_change_get(swigCPtr);
      return ret;
    } 
  }

  public int last_subscription_handle {
    set {
      cpscsharpmodulePINVOKE.PublicationMatchedStatus_last_subscription_handle_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.PublicationMatchedStatus_last_subscription_handle_get(swigCPtr);
      return ret;
    } 
  }

  public PublicationMatchedStatus() : this(cpscsharpmodulePINVOKE.new_PublicationMatchedStatus(), true) {
  }

}
