/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class QosPolicyCount : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal QosPolicyCount(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(QosPolicyCount obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~QosPolicyCount() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_QosPolicyCount(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int policy_id {
    set {
      cpscsharpmodulePINVOKE.QosPolicyCount_policy_id_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.QosPolicyCount_policy_id_get(swigCPtr);
      return ret;
    } 
  }

  public int count {
    set {
      cpscsharpmodulePINVOKE.QosPolicyCount_count_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.QosPolicyCount_count_get(swigCPtr);
      return ret;
    } 
  }

  public QosPolicyCount() : this(cpscsharpmodulePINVOKE.new_QosPolicyCount(), true) {
  }

}
