/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class QueryCondition2 : ReadCondition2 {
  private HandleRef swigCPtr;

  internal QueryCondition2(IntPtr cPtr, bool cMemoryOwn) : base(cpscsharpmodulePINVOKE.QueryCondition2_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(QueryCondition2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~QueryCondition2() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_QueryCondition2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public QueryCondition2(QueryCondition condition) : this(cpscsharpmodulePINVOKE.new_QueryCondition2(QueryCondition.getCPtr(condition)), true) {
  }

  public QueryCondition getQueryCondition() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.QueryCondition2_getQueryCondition(swigCPtr);
    QueryCondition ret = (cPtr == IntPtr.Zero) ? null : new QueryCondition(cPtr, false);
    return ret;
  }

  public string get_query_expression() {
    string ret = cpscsharpmodulePINVOKE.QueryCondition2_get_query_expression(swigCPtr);
    return ret;
  }

  public int get_query_parameters(StringSeq query_parameters) {
    int ret = cpscsharpmodulePINVOKE.QueryCondition2_get_query_parameters(swigCPtr, StringSeq.getCPtr(query_parameters));
    if (cpscsharpmodulePINVOKE.SWIGPendingException.Pending) throw cpscsharpmodulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int set_query_parameters(StringSeq query_parameters) {
    int ret = cpscsharpmodulePINVOKE.QueryCondition2_set_query_parameters(swigCPtr, StringSeq.getCPtr(query_parameters));
    if (cpscsharpmodulePINVOKE.SWIGPendingException.Pending) throw cpscsharpmodulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
