/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ReadCondition2 : Condition2 {
  private HandleRef swigCPtr;

  internal ReadCondition2(IntPtr cPtr, bool cMemoryOwn) : base(cpscsharpmodulePINVOKE.ReadCondition2_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ReadCondition2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ReadCondition2() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_ReadCondition2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ReadCondition2(ReadCondition condition) : this(cpscsharpmodulePINVOKE.new_ReadCondition2(ReadCondition.getCPtr(condition)), true) {
  }

  public ReadCondition getReadCondition() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.ReadCondition2_getReadCondition(swigCPtr);
    ReadCondition ret = (cPtr == IntPtr.Zero) ? null : new ReadCondition(cPtr, false);
    return ret;
  }

  public uint get_sample_state_mask() {
    uint ret = cpscsharpmodulePINVOKE.ReadCondition2_get_sample_state_mask(swigCPtr);
    return ret;
  }

  public uint get_view_state_mask() {
    uint ret = cpscsharpmodulePINVOKE.ReadCondition2_get_view_state_mask(swigCPtr);
    return ret;
  }

  public uint get_instance_state_mask() {
    uint ret = cpscsharpmodulePINVOKE.ReadCondition2_get_instance_state_mask(swigCPtr);
    return ret;
  }

  public DataReader2 get_datareader() {
    DataReader2 ret = new DataReader2(cpscsharpmodulePINVOKE.ReadCondition2_get_datareader(swigCPtr), true);
    return ret;
  }

}
