/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum ReliabilityQosPolicyKind {
  BEST_EFFORT_RELIABILITY_QOS = 1,
  RELIABLE_RELIABILITY_QOS
}
