/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ReliabilityQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ReliabilityQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ReliabilityQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ReliabilityQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_ReliabilityQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public ReliabilityQosPolicyKind kind {
    set {
      cpscsharpmodulePINVOKE.ReliabilityQosPolicy_kind_set(swigCPtr, (int)value);
    } 
    get {
      ReliabilityQosPolicyKind ret = (ReliabilityQosPolicyKind)cpscsharpmodulePINVOKE.ReliabilityQosPolicy_kind_get(swigCPtr);
      return ret;
    } 
  }

  public Duration_t max_blocking_time {
    set {
      cpscsharpmodulePINVOKE.ReliabilityQosPolicy_max_blocking_time_set(swigCPtr, Duration_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.ReliabilityQosPolicy_max_blocking_time_get(swigCPtr);
      Duration_t ret = (cPtr == IntPtr.Zero) ? null : new Duration_t(cPtr, false);
      return ret;
    } 
  }

  public ReliabilityQosPolicy() : this(cpscsharpmodulePINVOKE.new_ReliabilityQosPolicy(), true) {
  }

}
