/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ResourceLimitsQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ResourceLimitsQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ResourceLimitsQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ResourceLimitsQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_ResourceLimitsQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int max_samples {
    set {
      cpscsharpmodulePINVOKE.ResourceLimitsQosPolicy_max_samples_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.ResourceLimitsQosPolicy_max_samples_get(swigCPtr);
      return ret;
    } 
  }

  public int max_instances {
    set {
      cpscsharpmodulePINVOKE.ResourceLimitsQosPolicy_max_instances_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.ResourceLimitsQosPolicy_max_instances_get(swigCPtr);
      return ret;
    } 
  }

  public int max_samples_per_instance {
    set {
      cpscsharpmodulePINVOKE.ResourceLimitsQosPolicy_max_samples_per_instance_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.ResourceLimitsQosPolicy_max_samples_per_instance_get(swigCPtr);
      return ret;
    } 
  }

  public ResourceLimitsQosPolicy() : this(cpscsharpmodulePINVOKE.new_ResourceLimitsQosPolicy(), true) {
  }

}
