/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SampleRejectedStatus : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SampleRejectedStatus(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SampleRejectedStatus obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SampleRejectedStatus() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_SampleRejectedStatus(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int total_count {
    set {
      cpscsharpmodulePINVOKE.SampleRejectedStatus_total_count_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.SampleRejectedStatus_total_count_get(swigCPtr);
      return ret;
    } 
  }

  public int total_count_change {
    set {
      cpscsharpmodulePINVOKE.SampleRejectedStatus_total_count_change_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.SampleRejectedStatus_total_count_change_get(swigCPtr);
      return ret;
    } 
  }

  public SampleRejectedStatusKind last_reason {
    set {
      cpscsharpmodulePINVOKE.SampleRejectedStatus_last_reason_set(swigCPtr, (int)value);
    } 
    get {
      SampleRejectedStatusKind ret = (SampleRejectedStatusKind)cpscsharpmodulePINVOKE.SampleRejectedStatus_last_reason_get(swigCPtr);
      return ret;
    } 
  }

  public int last_instance_handle {
    set {
      cpscsharpmodulePINVOKE.SampleRejectedStatus_last_instance_handle_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.SampleRejectedStatus_last_instance_handle_get(swigCPtr);
      return ret;
    } 
  }

  public SampleRejectedStatus() : this(cpscsharpmodulePINVOKE.new_SampleRejectedStatus(), true) {
  }

}
