/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SampleInfo2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SampleInfo2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SampleInfo2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SampleInfo2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_SampleInfo2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SampleInfo2() : this(cpscsharpmodulePINVOKE.new_SampleInfo2(), true) {
  }

  public SampleInfo getSampleInfo() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.SampleInfo2_getSampleInfo(swigCPtr);
    SampleInfo ret = (cPtr == IntPtr.Zero) ? null : new SampleInfo(cPtr, false);
    return ret;
  }

}
