/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SampleLostStatus : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SampleLostStatus(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SampleLostStatus obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SampleLostStatus() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_SampleLostStatus(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int total_count {
    set {
      cpscsharpmodulePINVOKE.SampleLostStatus_total_count_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.SampleLostStatus_total_count_get(swigCPtr);
      return ret;
    } 
  }

  public int total_count_change {
    set {
      cpscsharpmodulePINVOKE.SampleLostStatus_total_count_change_set(swigCPtr, value);
    } 
    get {
      int ret = cpscsharpmodulePINVOKE.SampleLostStatus_total_count_change_get(swigCPtr);
      return ret;
    } 
  }

  public SampleLostStatus() : this(cpscsharpmodulePINVOKE.new_SampleLostStatus(), true) {
  }

}
