/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class StatusCondition : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StatusCondition(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(StatusCondition obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~StatusCondition() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_StatusCondition(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public bool b_trigger_value {
    set {
      cpscsharpmodulePINVOKE.StatusCondition_b_trigger_value_set(swigCPtr, value);
    } 
    get {
      bool ret = cpscsharpmodulePINVOKE.StatusCondition_b_trigger_value_get(swigCPtr);
      return ret;
    } 
  }

  public uint condition_type {
    set {
      cpscsharpmodulePINVOKE.StatusCondition_condition_type_set(swigCPtr, value);
    } 
    get {
      uint ret = cpscsharpmodulePINVOKE.StatusCondition_condition_type_get(swigCPtr);
      return ret;
    } 
  }

  public StatusCondition() : this(cpscsharpmodulePINVOKE.new_StatusCondition(), true) {
  }

}
