/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SubscriptionBuiltinTopicData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SubscriptionBuiltinTopicData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SubscriptionBuiltinTopicData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SubscriptionBuiltinTopicData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_SubscriptionBuiltinTopicData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public BuiltinTopicKey_t key {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_key_set(swigCPtr, BuiltinTopicKey_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_key_get(swigCPtr);
      BuiltinTopicKey_t ret = (cPtr == IntPtr.Zero) ? null : new BuiltinTopicKey_t(cPtr, false);
      return ret;
    } 
  }

  public BuiltinTopicKey_t participant_key {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_participant_key_set(swigCPtr, BuiltinTopicKey_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_participant_key_get(swigCPtr);
      BuiltinTopicKey_t ret = (cPtr == IntPtr.Zero) ? null : new BuiltinTopicKey_t(cPtr, false);
      return ret;
    } 
  }

  public string topic_name {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_topic_name_set(swigCPtr, value);
    } 
    get {
      string ret = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_topic_name_get(swigCPtr);
      return ret;
    } 
  }

  public string type_name {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_type_name_set(swigCPtr, value);
    } 
    get {
      string ret = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_type_name_get(swigCPtr);
      return ret;
    } 
  }

  public DurabilityQosPolicy durability {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_durability_set(swigCPtr, DurabilityQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_durability_get(swigCPtr);
      DurabilityQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new DurabilityQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public DeadlineQosPolicy deadline {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_deadline_set(swigCPtr, DeadlineQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_deadline_get(swigCPtr);
      DeadlineQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new DeadlineQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public LatencyBudgetQosPolicy latency_budget {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_latency_budget_set(swigCPtr, LatencyBudgetQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_latency_budget_get(swigCPtr);
      LatencyBudgetQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new LatencyBudgetQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public LivelinessQosPolicy liveliness {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_liveliness_set(swigCPtr, LivelinessQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_liveliness_get(swigCPtr);
      LivelinessQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new LivelinessQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public ReliabilityQosPolicy reliability {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_reliability_set(swigCPtr, ReliabilityQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_reliability_get(swigCPtr);
      ReliabilityQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new ReliabilityQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public OwnershipQosPolicy ownership {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_ownership_set(swigCPtr, OwnershipQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_ownership_get(swigCPtr);
      OwnershipQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new OwnershipQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public DestinationOrderQosPolicy destination_order {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_destination_order_set(swigCPtr, DestinationOrderQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_destination_order_get(swigCPtr);
      DestinationOrderQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new DestinationOrderQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public UserDataQosPolicy user_data {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_user_data_set(swigCPtr, UserDataQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_user_data_get(swigCPtr);
      UserDataQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new UserDataQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public TimeBasedFilterQosPolicy time_based_filter {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_time_based_filter_set(swigCPtr, TimeBasedFilterQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_time_based_filter_get(swigCPtr);
      TimeBasedFilterQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new TimeBasedFilterQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public PresentationQosPolicy presentation {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_presentation_set(swigCPtr, PresentationQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_presentation_get(swigCPtr);
      PresentationQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new PresentationQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public PartitionQosPolicy partition {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_partition_set(swigCPtr, PartitionQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_partition_get(swigCPtr);
      PartitionQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new PartitionQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public TopicDataQosPolicy topic_data {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_topic_data_set(swigCPtr, TopicDataQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_topic_data_get(swigCPtr);
      TopicDataQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new TopicDataQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public GroupDataQosPolicy group_data {
    set {
      cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_group_data_set(swigCPtr, GroupDataQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.SubscriptionBuiltinTopicData_group_data_get(swigCPtr);
      GroupDataQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new GroupDataQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public SubscriptionBuiltinTopicData() : this(cpscsharpmodulePINVOKE.new_SubscriptionBuiltinTopicData(), true) {
  }

}
