/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum SUPPORT_TYPE {
  DDS_STRING_TYPE,
  DDS_INTEGER32_TYPE,
  DDS_FLOAT_TYPE,
  DDS_CHARACTER_TYPE,
  DDS_STRUCT_TYPE
}
