/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class TimeBasedFilterQosPolicy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TimeBasedFilterQosPolicy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TimeBasedFilterQosPolicy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TimeBasedFilterQosPolicy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_TimeBasedFilterQosPolicy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Duration_t minimum_separation {
    set {
      cpscsharpmodulePINVOKE.TimeBasedFilterQosPolicy_minimum_separation_set(swigCPtr, Duration_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TimeBasedFilterQosPolicy_minimum_separation_get(swigCPtr);
      Duration_t ret = (cPtr == IntPtr.Zero) ? null : new Duration_t(cPtr, false);
      return ret;
    } 
  }

  public TimeBasedFilterQosPolicy() : this(cpscsharpmodulePINVOKE.new_TimeBasedFilterQosPolicy(), true) {
  }

}
