/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class TopicDescription2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TopicDescription2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TopicDescription2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TopicDescription2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_TopicDescription2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public TopicDescription2(TopicDescription topicDescription) : this(cpscsharpmodulePINVOKE.new_TopicDescription2(TopicDescription.getCPtr(topicDescription)), true) {
  }

  public TopicDescription getTopicDescription() {
    IntPtr cPtr = cpscsharpmodulePINVOKE.TopicDescription2_getTopicDescription(swigCPtr);
    TopicDescription ret = (cPtr == IntPtr.Zero) ? null : new TopicDescription(cPtr, false);
    return ret;
  }

  public string get_type_name() {
    string ret = cpscsharpmodulePINVOKE.TopicDescription2_get_type_name(swigCPtr);
    return ret;
  }

  public string get_name() {
    string ret = cpscsharpmodulePINVOKE.TopicDescription2_get_name(swigCPtr);
    return ret;
  }

  public DomainParticipant2 get_participant() {
    DomainParticipant2 ret = new DomainParticipant2(cpscsharpmodulePINVOKE.TopicDescription2_get_participant(swigCPtr), true);
    return ret;
  }

}
