/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class TopicBuiltinTopicData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TopicBuiltinTopicData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TopicBuiltinTopicData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TopicBuiltinTopicData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cpscsharpmodulePINVOKE.delete_TopicBuiltinTopicData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public BuiltinTopicKey_t key {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_key_set(swigCPtr, BuiltinTopicKey_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_key_get(swigCPtr);
      BuiltinTopicKey_t ret = (cPtr == IntPtr.Zero) ? null : new BuiltinTopicKey_t(cPtr, false);
      return ret;
    } 
  }

  public string name {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_name_set(swigCPtr, value);
    } 
    get {
      string ret = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_name_get(swigCPtr);
      return ret;
    } 
  }

  public string type_name {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_type_name_set(swigCPtr, value);
    } 
    get {
      string ret = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_type_name_get(swigCPtr);
      return ret;
    } 
  }

  public DurabilityQosPolicy durability {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_durability_set(swigCPtr, DurabilityQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_durability_get(swigCPtr);
      DurabilityQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new DurabilityQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public DurabilityServiceQosPolicy durability_service {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_durability_service_set(swigCPtr, DurabilityServiceQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_durability_service_get(swigCPtr);
      DurabilityServiceQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new DurabilityServiceQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public DeadlineQosPolicy deadline {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_deadline_set(swigCPtr, DeadlineQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_deadline_get(swigCPtr);
      DeadlineQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new DeadlineQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public LatencyBudgetQosPolicy latency_budget {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_latency_budget_set(swigCPtr, LatencyBudgetQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_latency_budget_get(swigCPtr);
      LatencyBudgetQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new LatencyBudgetQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public LivelinessQosPolicy liveliness {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_liveliness_set(swigCPtr, LivelinessQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_liveliness_get(swigCPtr);
      LivelinessQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new LivelinessQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public ReliabilityQosPolicy reliability {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_reliability_set(swigCPtr, ReliabilityQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_reliability_get(swigCPtr);
      ReliabilityQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new ReliabilityQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public TransportPriorityQosPolicy transport_priority {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_transport_priority_set(swigCPtr, TransportPriorityQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_transport_priority_get(swigCPtr);
      TransportPriorityQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new TransportPriorityQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public LifespanQosPolicy lifespan {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_lifespan_set(swigCPtr, LifespanQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_lifespan_get(swigCPtr);
      LifespanQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new LifespanQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public DestinationOrderQosPolicy destination_order {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_destination_order_set(swigCPtr, DestinationOrderQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_destination_order_get(swigCPtr);
      DestinationOrderQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new DestinationOrderQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public HistoryQosPolicy history {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_history_set(swigCPtr, HistoryQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_history_get(swigCPtr);
      HistoryQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new HistoryQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public ResourceLimitsQosPolicy resource_limits {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_resource_limits_set(swigCPtr, ResourceLimitsQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_resource_limits_get(swigCPtr);
      ResourceLimitsQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new ResourceLimitsQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public OwnershipQosPolicy ownership {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_ownership_set(swigCPtr, OwnershipQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_ownership_get(swigCPtr);
      OwnershipQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new OwnershipQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public TopicDataQosPolicy topic_data {
    set {
      cpscsharpmodulePINVOKE.TopicBuiltinTopicData_topic_data_set(swigCPtr, TopicDataQosPolicy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cpscsharpmodulePINVOKE.TopicBuiltinTopicData_topic_data_get(swigCPtr);
      TopicDataQosPolicy ret = (cPtr == IntPtr.Zero) ? null : new TopicDataQosPolicy(cPtr, false);
      return ret;
    } 
  }

  public TopicBuiltinTopicData() : this(cpscsharpmodulePINVOKE.new_TopicBuiltinTopicData(), true) {
  }

}
